### ISSUE TITLE
Multipart Upload Issue(s)

### ISSUE THREAD

**Issue by gcstang** [oracle/oci-go-sdk#105]
go version 1.10.1
latest version of oci-go-sdk
Original File size: 368M
Split at 100MB then tried at 20MB
Original Error: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
I modified the file: common.client and changed timeout from 30 to 60 seconds.
First error went away now I have a second error:

net/http: HTTP/1.x transport connection broken: http: ContentLength=104857600 with Body length 385447926

After Change to smaller split size:
net/http: HTTP/1.x transport connection broken: http: ContentLength=20971520 with Body length 385447926

**Comment by gcstang** [comment]
yes it's for upload part api.

put object worked correctly.

**Comment by gcstang** [comment]
no proxy

**Comment by jasonyin** [comment]
For your first timeout error, you can either change the clientTimeout, but for larger object or unreliable network which takes un-predictable time to upload (wait for responseHeader come back). You could also set the http.Transport.ResponseHeaderTimeout to 0.

BTW, for "latest version of oci-go-sdk", were you referring to V1.2.0?

Looks like you are not using the default httpClient or http.Transport? If yes, could you pls share the code so I can try to repro the issue you have?

**Comment by gcstang** [comment]
I'm using the Latest version of Master and whatever httpClient is built into the code pkgs 
"github.com/oracle/oci-go-sdk/common"
"github.com/oracle/oci-go-sdk/example/helpers"
"github.com/oracle/oci-go-sdk/objectstorage"

**Comment by jasonyin** [comment]
I need more information to debug the issue, especially how you split the file into multi-parts. Sharing the code would be helpful, however, with limited information here, I noticed that the http.ContentLength is different than the body length which will cause golang http transport through error. Could be an bug around 'UploadPartBody' for UploadPartRequest. I would try to set it as 
```go
UploadPartBody: ioutil.NopCloser(bytes.NewReader(buffer)),
```

net/http: HTTP/1.x transport connection broken: http: ContentLength=**104857600** with Body length **385447926**

After Change to smaller split size:
net/http: HTTP/1.x transport connection broken: http: ContentLength=**20971520** with Body length **385447926**

**Comment by gcstang** [comment]
@jasonyin I'll put something together and  add it to the ticket but this is part of a larger application so it will take me a little while.

Not sure this small part will help, otherwise I'll work on the attachment.

`func (o *ObjStore) UploadPart(bucketName, objectName, uploadId string, partNo, contentLength int, content io.ReadCloser) *string {
	namespace := o.GetNamespace()
	request := objectstorage.UploadPartRequest{
		NamespaceName:&namespace,
		BucketName:&bucketName,
		ObjectName:&objectName,
		UploadId:&uploadId,
		UploadPartNum:&partNo,
		ContentLength:&contentLength,
		UploadPartBody:content,
	}

	r, err := o.client.UploadPart(*o.context, request)
	helpers.LogIfError(err)

	return r.ETag
}`

**Comment by jasonyin** [comment]
Thanks for sharing the info!

There are two key input parameters here, contentLength and content (in your sample code):

1. The contentLength is the length of the part you are uploading (100M or 20M in your error trace) which is correct;

2. Body length (shows in the error trace) is 368M fixed which looks wrong to me, it should be same as the part size you are uploading (i.e. 20M or 100M depends on the size of part), it's not the size of the file you are uploading (368M). The body length in the error trace comes from your content parameter( io.ReaderCloser), I suspect that the content parameter you are using was wrong.  Here is a sample code, hoping it helps to debug the issue:

```go
// make a buffer with partSize (i.e. 20M or 100M)
buffer := make([]byte, partSize)

// load content from the file you are uploading into a buffer
_, err := file.ReadAt(buffer, offset)

// try to update your code with following line, I think it most likely would fix the issue
content := ioutil.NopCloser(bytes.NewReader(buffer))

```

Please let me know if you have any questions/issues, thanks!

----------------------
net/http: HTTP/1.x transport connection broken: http: ContentLength=**104857600** with Body length **385447926**

After Change to smaller split size:
net/http: HTTP/1.x transport connection broken: http: ContentLength=**20971520** with Body length **385447926**

**Comment by gcstang** [comment]
I found the issue with this particular piece but I'm now looking into the CommitMultipartUpload and UploadPart I'm getting an error: 
`
time="2018-04-09T17:48:49-05:00" level=debug msg="Starting Upload: tmp/tmp_1 Size: 20971520"
time="2018-04-09T17:48:56-05:00" level=debug msg="Etag: 6972A5FD95547EAFE0530292F20ABF0A"
time="2018-04-09T17:49:07-05:00" level=debug msg="Starting Upload: tmp/tmp_2 Size: 20971520"
time="2018-04-09T17:49:14-05:00" level=debug msg="Etag: 6972A5FD95637EAFE0530292F20ABF0A"
time="2018-04-09T17:49:19-05:00" level=debug msg="Starting Upload: tmp/tmp_3 Size: 20971520"
time="2018-04-09T17:49:27-05:00" level=debug msg="Etag: 69731F57E278DE36E0530292F20A8AA6"
time="2018-04-09T17:49:29-05:00" level=debug msg="Starting Upload: tmp/tmp_4 Size: 20971520"
time="2018-04-09T17:49:37-05:00" level=debug msg="Etag: 6972A5FD95987EAFE0530292F20ABF0A"
time="2018-04-09T17:49:40-05:00" level=debug msg="Starting Upload: tmp/tmp_5 Size: 20971520"
time="2018-04-09T17:49:47-05:00" level=debug msg="Etag: 69729C2AED8177DFE0530292F20AA579"
time="2018-04-09T17:49:47-05:00" level=debug msg="Starting Upload: tmp/tmp_6 Size: 20971520"
time="2018-04-09T17:49:55-05:00" level=debug msg="Etag: 69731F57E2AADE36E0530292F20A8AA6"
time="2018-04-09T17:49:55-05:00" level=debug msg="Starting Upload: tmp/tmp_7 Size: 20971520"
time="2018-04-09T17:50:02-05:00" level=debug msg="Etag: 69729C2AEDA077DFE0530292F20AA579"
time="2018-04-09T17:50:02-05:00" level=debug msg="Starting Upload: tmp/tmp_8 Size: 20971520"
time="2018-04-09T17:50:09-05:00" level=debug msg="Etag: 6972A5FD95DD7EAFE0530292F20ABF0A"
time="2018-04-09T17:50:09-05:00" level=debug msg="Starting Upload: tmp/tmp_9 Size: 20971520"
time="2018-04-09T17:50:17-05:00" level=debug msg="Etag: 69731F57E2D0DE36E0530292F20A8AA6"
time="2018-04-09T17:50:17-05:00" level=debug msg="Starting Upload: tmp/tmp_10 Size: 20971520"
time="2018-04-09T17:50:24-05:00" level=debug msg="Etag: 69729C2AEDCE77DFE0530292F20AA579"
time="2018-04-09T17:50:24-05:00" level=debug msg="Starting Upload: tmp/tmp_11 Size: 20971520"
time="2018-04-09T17:50:31-05:00" level=debug msg="Etag: 69729C2AEDDE77DFE0530292F20AA579"
time="2018-04-09T17:50:31-05:00" level=debug msg="Starting Upload: tmp/tmp_12 Size: 20971520"
time="2018-04-09T17:50:38-05:00" level=debug msg="Etag: 69731F57E2F5DE36E0530292F20A8AA6"
time="2018-04-09T17:50:38-05:00" level=debug msg="Starting Upload: tmp/tmp_13 Size: 20971520"
time="2018-04-09T17:50:46-05:00" level=debug msg="Etag: 69729C2AEDEF77DFE0530292F20AA579"
time="2018-04-09T17:50:46-05:00" level=debug msg="Starting Upload: tmp/tmp_14 Size: 20971520"
time="2018-04-09T17:50:53-05:00" level=debug msg="Etag: 69731F57E312DE36E0530292F20A8AA6"
time="2018-04-09T17:50:53-05:00" level=debug msg="Starting Upload: tmp/tmp_15 Size: 20971520"
time="2018-04-09T17:51:00-05:00" level=debug msg="Etag: 6972A5FD96437EAFE0530292F20ABF0A"
time="2018-04-09T17:51:00-05:00" level=debug msg="Starting Upload: tmp/tmp_16 Size: 20971520"
time="2018-04-09T17:51:07-05:00" level=debug msg="Etag: 69729C2AEE2277DFE0530292F20AA579"
time="2018-04-09T17:51:07-05:00" level=debug msg="Starting Upload: tmp/tmp_17 Size: 20971520"
time="2018-04-09T17:51:14-05:00" level=debug msg="Etag: 69731F57E34FDE36E0530292F20A8AA6"
time="2018-04-09T17:51:14-05:00" level=debug msg="Starting Upload: tmp/tmp_18 Size: 20971520"
time="2018-04-09T17:51:22-05:00" level=debug msg="Etag: 69729C2AEE4177DFE0530292F20AA579"
time="2018-04-09T17:51:22-05:00" level=debug msg="Starting Upload: tmp/tmp_19 Size: 7960566"
time="2018-04-09T17:51:25-05:00" level=debug msg="Etag: 69729C2AEE4A77DFE0530292F20AA579"
2018/04/09 17:52:04 Service error:InvalidUploadPart. There were some invalid part (partNum/etag) combination for the upload UploadKey{objectKey=ObjectKey{bucket=BucketKey{namespace='oraclegbudev', name='test1', api='Api{version='v2'}', bucketId='BucketId{id=LL86GzNiGW122L5iu/Fquw-orac-test}'}, name='Docker.dmg'}, uploadId='8972eafd-fbb0-0175-85ab-332b95a0633a'}. http status code: 400
`

**Comment by jasonyin** [comment]
glad you got the issue resolved, could you pls share the root cause for the issue? is it because the upload part stream you were using was entire file not the split part?

**Comment by gcstang** [comment]
@jasonyin yes I had a typo in there (wrong var)
