### ISSUE TITLE
Issues with building Packer on the Windows platform due to number of files in oci-go-sdk/core package and limitation of golang's compile on windows

### ISSUE THREAD

**Issue by prydie** [oracle/oci-go-sdk#108]
Our merge of the OCI Go SDK into Packer has broken builds under certain circumstances in Windows.

We should reduce the number of generated files in the core package to resolve.

See: https://github.com/hashicorp/packer/issues/6220

**Comment by jasonyin** [comment]
thanks for reporting the issue. Is it an error for large number of files in core package or is it the length of the absolute path is too long?

**Comment by eginez** [comment]
@prydie How do we reproduce this issue? Can we get access to the log with the build failures?

**Comment by eginez** [comment]
I was able to verify both our sdk and packer builds on windows if the GOPATH is not too big (< 100 chars). Thus any customer that needs to build package will have to be aware of such limitation on windows. Further the right fix should be at the compiler level, there is not much we can do in the sdk that will fix this, given that in the future we are planning new files to different packages. Thoughts?

**Comment by jasonyin** [comment]
will update the document about this known issue in next release.
