### ISSUE TITLE
In the case of attaching an already attached volume, how do I get the http status code?

### ISSUE THREAD

**Issue by MadalinaPatrichi** [oracle/oci-go-sdk#112]
We have recently ungraded out oci-go-sdk version from 1.0.0 to 1.5.0 and in the process I've noticed that in the case where I'm trying to attach a volume twice, the error comes back, however, the response is nil. What is the recommended way of extracting the http status code in this case? Has the API changed when it comes to this?

**Comment by jasonyin** [comment]
The API return two structs, one is response, the other one is err. Would the err works for you?

func (client ComputeClient) AttachVolume(ctx context.Context, request AttachVolumeRequest) (response AttachVolumeResponse, **err error**)

**Comment by MadalinaPatrichi** [comment]
The status code of the request is not easily extracted from the error. This used to be available in the response, but it seems like there was an API change. Is this documented anywhere to explain  why this has happened and how are we supposed to

**Comment by jasonyin** [comment]
@MadalinaPatrichi , please let us know if you are still having the issue or not, otherwise, we are going to close it, thanks!

**Comment by jasonyin** [comment]
@MadalinaPatrichi I am closing this issue, please let us know if you still have questions, thanks!
