### ISSUE TITLE
Please add a way how to launch multiple instances at a time.

### ISSUE THREAD

**Issue by mixaal** [oracle/oci-go-sdk#113]
Hi,

Could you please add a way how to launch multiple instances at a time. The synopsis would be similar to the `LaunchInstance()` method, but it would take an additional parameter `NumberOfInstances`. E.g.:

```
func (o *OciCompute) LaunchInstances(numberOfInstances int, request LaunchInstanceRequest) ([]LaunchInstanceResponse, error)
```

The advantage can be in fact that spawning multiple uniform instances on the backend might be faster rather than calling multiple parallel single `LaunchInstance()` requests in multiple threads from the client. Also network traffic and number of requests issued on the backend is more effiecient (1 : N).

Thanks.

**Comment by jasonyin** [comment]
Were you asking an new API to lunch multiple instance at once?
If yes, this would be an ask to the service team, not SDK. I can help to redirect this request to our service team

**Comment by mixaal** [comment]
Please redirect the request to the right folks. I assume when oci service supports multiple instance lunch from one request there's still a need to enhance the SDK to support it.

**Comment by eginez** [comment]
Nothing to do in the sdk side for this concern
