### ISSUE TITLE
createKubeconfig function should not close http reponse body

### ISSUE THREAD

**Issue by waynz0r** [oracle/oci-go-sdk#116]
Hi,

the defer common.CloseBodyIfValid(httpResponse) call in the containerengine.createKubeconfig function closes the http body which makes impossible to get the content of it.

> // createKubeconfig implements the OCIOperation interface (enables retrying operations)
> func (client ContainerEngineClient) createKubeconfig(ctx context.Context, request common.OCIRequest) (common.OCIResponse, error) {
> 	httpRequest, err := request.HTTPRequest(http.MethodPost, "/clusters/{clusterId}/kubeconfig/content")
> 	if err != nil {
> 		return nil, err
> 	}
> 
> 	var response CreateKubeconfigResponse
> 	var httpResponse *http.Response
> 	httpResponse, err = client.Call(ctx, &httpRequest)
> 	defer common.CloseBodyIfValid(httpResponse)
> 	response.RawResponse = httpResponse
> 	if err != nil {
> 		return response, err
> 	}
> 
> 	err = common.UnmarshalResponse(httpResponse, &response)
> 	return response, err
> }

Thanks!

**Comment by jasonyin** [comment]
thanks for reporting this issue and submit the PR, I am looking at the PR now.

**Comment by bonifaido** [comment]
Hi @jasonyin, just a question, will be the new SDK released today?

**Comment by jasonyin** [comment]
fixed in https://github.com/oracle/oci-go-sdk/releases/tag/v2.0.0
