### ISSUE TITLE
Add support for tagging load balancers

### ISSUE THREAD

**Issue by jhorwit2** [oracle/oci-go-sdk#118]
https://docs.cloud.oracle.com/iaas/releasenotes/changes/9ced7d70-005a-4aa1-a47a-213dd8d2dcad/

**Comment by jodoglevy** [comment]
This is currently planned for our next milestone and should be released shortly. Thanks for reporting.

**Comment by jasonyin** [comment]
released in https://github.com/oracle/oci-go-sdk/releases/tag/v2.0.0
