### ISSUE TITLE
OCI error is missing opc-request-id value

### ISSUE THREAD

**Issue by jhorwit2** [oracle/oci-go-sdk#120]
Responses from OCI include an ID that's extremely valuable when debugging failed requests, which is set on the response header opc-request-id. The error returned from the go sdk should include that which matches how other sdks, like the [java one](https://github.com/oracle/oci-java-sdk/blob/master/bmc-common/src/main/java/com/oracle/bmc/model/BmcException.java#L40), exposes errors.

**Comment by jasonyin** [comment]
hi @jhorwit2, thanks for reporting this issue. The opc-request-id is defined in most response structs (if defined by the spec), are you referring to the case of service failure, add this id to the error?

**Comment by jhorwit2** [comment]
Yes @jasonyin

**Comment by jhorwit2** [comment]
Currently, if a request fails the response struct will be nil and the error struct won't have the value. This results in us being unable to provide support with the information they need to investigate api errors/bugs.

**Comment by jhorwit2** [comment]
@jasonyin i have a fork with this functionality since i need it for an SR. If you want I can open up a PR?

**Comment by jasonyin** [comment]
this is been fixed in v2.1.0 https://github.com/oracle/oci-go-sdk/releases/tag/v2.1.0 
the common.ServiceError now have a method GetOpcRequestID()

**Comment by jhorwit2** [comment]
@jasonyin that code looks potentially like it can panic. You're checking if `ociResponse` isn't nil on error then assuming in `newServiceFailureFromResponse` that it's always not nil.

**Comment by jhorwit2** [comment]
Actually, it would panic if the operation failed prior to initiating the request. For example, if the http request isn't valid, then ociResponse would be nil. 

https://github.com/oracle/oci-go-sdk/blob/master/core/core_compute_client.go#L682-L700

Or if the pre-request steps of the common base client error out. 

https://github.com/oracle/oci-go-sdk/blob/master/common/client.go#L265-L280

**Comment by jhorwit2** [comment]
Nvm.
