### ISSUE TITLE
Object Store ListObjects nil for Size, MD5 and Created

### ISSUE THREAD

**Issue by gcstang** [oracle/oci-go-sdk#123]
go version go1.10.3 darwin/amd64
oci-go-sdk 2.2.0

Hello it seems as though these values don't come through using the oci-go-sdk vs. the oci command?

oci os object list -bn <bucketname> --namespace <namespace>

**Comment by jodoglevy** [comment]
Hi,

From the [Go SDK API Reference](https://godoc.org/github.com/oracle/oci-go-sdk/objectstorage#ListObjectsRequest) for this request:

```
// Object summary in list of objects includes the 'name' field. This parameter can also include 'size'
// (object size in bytes), 'md5', and 'timeCreated' (object creation date and time) fields.
// Value of this parameter should be a comma-separated, case-insensitive list of those field names.
// For example 'name,timeCreated,md5'.
Fields *string `mandatory:"false" contributesTo:"query" name:"fields" omitEmpty:"true"`
```

So if you set this field to "name,size,md5,timeCreated" you'll get back these fields.

**Comment by gcstang** [comment]
Thank you!
