### ISSUE TITLE
Implementation example of SourceDetails in LaunchInstanceDetails

### ISSUE THREAD

**Issue by schmidtp0740** [oracle/oci-go-sdk#125]
refer to https://stackoverflow.com/questions/52011758/example-of-launchinstance-with-instancesourcedetails-interface

looking for an example of an implementation of an interface for SourceDetails in laynchInstanceDetails.

**Comment by schmidtp0740** [comment]
nvm i figured out how to do it by the following. Maybe it would be best to update the docs in the example to show this
```
var instanceSD core.InstanceSourceDetails = core.InstanceSourceViaImageDetails{
		ImageId:             common.String("ocid1.image.oc1.iad.aaaaaaaa2tq67tvbeavcmioghquci6p3pvqwbneq3vfy7fe7m7geiga4cnxa"),
		BootVolumeSizeInGBs: common.Int64(50),
	}

	instanceRequest.SourceDetails = instanceSD
```

**Comment by jasonyin** [comment]
hi @schmidtp0740 thanks for reporting this, glad to see you figured it out. This is related with 'Polymorphic Json' which we have a samilar example here https://github.com/oracle/oci-go-sdk/blob/master/example/example_core_test.go#L114

**Comment by jasonyin** [comment]
I am closing this issue, pls let us know if you still need further support, thanks!
