### ISSUE TITLE
the signing algorithm does not lower case the header fields 

### ISSUE THREAD

**Issue by jhorwit2** [oracle/oci-go-sdk#132]
https://tools.ietf.org/html/draft-cavage-http-signatures-10#section-2.3

> Create the header field string by concatenating the lowercased header field name followed with an ASCII colon `:`, an ASCII space ` `, and the header field value. 

https://github.com/oracle/oci-go-sdk/blob/master/common/http_signer.go#L108-L130

This can causes signatures to fail verification between client and server. `part` in the code above should be passed through `strings.ToLower`

**Comment by jasonyin** [comment]
@jhorwit2 thanks for reporting the issue. Did you see any request sign failures for this case?

**Comment by jasonyin** [comment]
if yes, could you pls send me a opc-request-id, thanks!

**Comment by jasonyin** [comment]
This has been fixed in v2.7.0, pls let us know if you still seeing the issue.
