### ISSUE TITLE
rawConfigurationProvider does not work with compositeConfigurationProvider

### ISSUE THREAD

**Issue by anilarora** [oracle/oci-go-sdk#134]
Noticed this issue when trying to use the rawConfigurationProvider with the compositeConfigurationProvider.  The compositeConfigurationProvider checks if an error is returned from the delegate configuration provider.  However, the rawConfigurationProvider does not return an error if the value is an empty string or nil.  So, if the rawConfigurationProvider is used at the beginning of the slice, it's possible an empty value can be returned from any of the interface methods.

Either the compositeConfigurationProvider needs to also check if the value returned from the delegate is empty or nil or the rawConfigurationProvider needs to return an error if the value is empty or nil.

**Comment by eginez** [comment]
@anilarora Thanks for reporting this issue. A fix for it will be available in our next release

**Comment by jasonyin** [comment]
This has been fixed in v2.7.0, pls let us know if you still seeing the issue.
