### ISSUE TITLE
Can't find GetObject in OCI go SDK Object Storage

### ISSUE THREAD

**Issue by HenryXie1** [oracle/oci-go-sdk#137]
Hi there:
  I searched  https://godoc.org/github.com/oracle/oci-go-sdk/objectstorage
  I find PutObject to upload files  but I don't find GetObject to download files
  Am I missing sth?  Also in the sdk examples, can you provide examples to download files?

Thanks
Henry

**Comment by jasonyin** [comment]
You can find it here https://github.com/oracle/oci-go-sdk/blob/master/objectstorage/objectstorage_client.go#L652.

For samples, it's a simple GET operation just like the ObjectStorage get namespace sample here: https://github.com/oracle/oci-go-sdk/blob/master/example/example_objectstorage_test.go#L59.

**Comment by syerabat** [comment]
Hi Jasonyin,
I followed the above fix but it is not downloading the actual file.  I am able to get file metadata though. Could you please advise?

Below is my code:

func getObject(ctx context.Context, c objectstorage.ObjectStorageClient, namespace, bucketname, objectname string) error {
	request := objectstorage.GetObjectRequest {
		NamespaceName: &namespace,
		BucketName:    &bucketname,
		ObjectName:    &objectname,
	}
	out2, err := c.GetObject(ctx, request)
	fmt.Println(*out2.ContentMd5) //gets the file md5sum value.
	//fmt.Println("out2 value", out2) //Getting file metadata
	helpers.FatalIfError(err)
	return err
}
