### ISSUE TITLE
CreateClusterDetails Options is required 

### ISSUE THREAD

**Issue by stevensu1977** [oracle/oci-go-sdk#139]
// Optional attributes for the cluster.
 Options *ClusterCreateOptions `mandatory:"false" json:"options"`

 mandatory is false, but when I use api get   "Service error:InvalidParameter. options can't be empty"

**Comment by jasonyin** [comment]
thanks for reporting this issue. We will look into this.

**Comment by scottsbaldwin** [comment]
Thanks @stevensu1977 for reporting this issue. It looks like some additional validation is occurring on the backend that is not in sync with the `mandatory:"false"` declaration.

The workaround for now is to specify `Options`. The `Options` field must be non-nil at the moment and can have none of the options actually set. The field just needs to be present.

**Comment by eginez** [comment]
I am inquiring with the service owners to resolve this issue as I don't see the field has changed in the latest releases

**Comment by eginez** [comment]
The service team is still working on this fix, no ETA at the moment

**Comment by jodoglevy** [comment]
This is now fixed -- CreateClusterDetails's options field is now optional in the service.
