### ISSUE TITLE
Shorthand for toronto-1 missing

### ISSUE THREAD

**Issue by faiq** [oracle/oci-go-sdk#154]
Hey y'all the YYZ shorthand is missing for parsing the string to region. That option is available for all other regions. Here is a link to the official documentation: https://docs.cloud.oracle.com/iaas/Content/General/Concepts/regions.htm that states YYZ is an acceptable key. 

Here is the line of code that needs to change https://github.com/oracle/oci-go-sdk/blob/master/common/common.go#L101

Thanks so much for all you do!

**Comment by eginez** [comment]
@faiq  Thanks for the report we are looking into this

**Comment by jasonyin** [comment]
@faiq tanks for reporting the issue. The region short name is an optional, I am wondering what's your use case for that one?

**Comment by jasonyin** [comment]
@faiq, pls let us know if you are having issue to use the new regions or your use cases on the region keys, otherwise, I am going to close it by the end of tomorrow, thanks!

**Comment by faiq** [comment]
I was using the region keys for the grafana datasource for OCI, to make a shorter display for the users. I changed it to using the full region names, but I think we're going to run into this problem again and it would be best to be consistent in our support.

**Comment by jasonyin** [comment]
@faiq , for grafana, you can put anything as a filter dimension which has nothing related with SDK in terms of public support. FYI, region key is optional, region values is always guaranteed to be there for all SDKs and other clients. I am closing this issue, pls let me know if you have different opinions, thanks!

**Comment by faiq** [comment]
I was talking about the plugin I was writing for Grafana which is here: https://github.com/oracle/oci-grafana-plugin

I think it would be best if the behavior was consistent and considering that its a 5 character change I don't see why we don't just make it?
