### ISSUE TITLE
The 'tag' info is always ignored in the returned string of Version() function

### ISSUE THREAD

**Issue by zehliu** [oracle/oci-go-sdk#157]
A minor issue with the [Version()](https://github.com/oracle/oci-go-sdk/blob/0306ff0303b6c9f6ea6458021adc9f8f09f562b0/common/version.go#L22) function, looks like the 'tag' info would never be displayed in the returned string. Because the [WriteString()](https://golang.org/pkg/bytes/#Buffer.WriteString) method of bytes.Buffer always returns a nil error, the 'if' condition always evaluates true.
https://github.com/oracle/oci-go-sdk/blob/0306ff0303b6c9f6ea6458021adc9f8f09f562b0/cmd/genver/version_template.go#L32

**Comment by jasonyin** [comment]
@zehliu thanks for reporting the issue, we are looking into this.

**Comment by jasonyin** [comment]
@zehliu we will fix it in next coming release
