### ISSUE TITLE
Undocumented RawConfigurationProvider

### ISSUE THREAD

**Issue by StuporHero** [oracle/oci-go-sdk#170]
[`common.NewRawConfigurationProvider`](https://github.com/oracle/oci-go-sdk/blob/366e0557b30ee26f689eaa9ab5a1d1e252077c55/common/configuration.go#L55) is not documented in the README.md, and I'm wondering if it is undocumented on purpose. In other words, should it not be considered a part of the public API and therefore subject to change without notice, or is it safe to use?

**Comment by eginez** [comment]
You are welcome to use `common.NewRawConfigurationProvider` as is an exposed function of the sdk. I am fixing the documentation to make it point to all the implementations of `ConfigurationProvider` that can be used

**Comment by eginez** [comment]
Fixed in #173 
I have added modified the README doc to clarify the implementations of `ConfigurationProvider`
