### ISSUE TITLE
OCI Golang SDK hook/callback to display progressbar for uploads.

### ISSUE THREAD

**Issue by satyavvd** [oracle/oci-go-sdk#187]
While uploading files into object storage using Golang OCI SDK,
     I would like to display a progress bar while upload ( files are huge in
     size), anyhow I don't see a hook/callback provided in Go SDK to display progress on progress
     bar(unlike python sdk) for multi part uploads.

**Comment by jasonyin** [comment]
fixed in https://github.com/oracle/oci-go-sdk/releases/tag/v12.0.0
