### ISSUE TITLE
how would be possible to give the oci acocunts setting in the code without calling or using any external datasources

### ISSUE THREAD

**Issue by eugsim1** [oracle/oci-go-sdk#202]
Hello team
quick ans easy question 
for a workshop we need to distribute an oci utility that will dump several oci config 
I have written a very simpe go utilty where i can load in my linux env withTF_ my oci seeting and then i can call this code  to log in and run my code :

e1 := common.ConfigurationProviderEnvironmentVariables("TF_VAR","")
//fmt.Println(e1)

// The OCID of the tenancy containing the compartment.
TenancyOCID, err := e1.TenancyOCID()
	if err != nil {
	fmt.Println("Error TenancyOCID :", err)
	return
}

UserOCID, err :=    e1.UserOCID()
	if err != nil {
	fmt.Println("Error UserOCID :", err)
	return
}
	
KeyFingerprint, err := e1.KeyFingerprint()
	if err != nil {
	fmt.Println("Error KeyFingerprint :", err)
	return
}

Region, err := e1.Region()
	if err != nil {
	fmt.Println("Error Region :", err)
	return
}

how would i code inside my functions the previous values that i m reading from the linux env ?
thanks
eugene

**Comment by buzhidao77** [comment]
Hi @eugsim1 
Could you please elaborate a little bit more on "previous values" part?

**Comment by eugsim1** [comment]
yes i m having my own env with TF_vars and reading the docs i thought that i wouldnt be possible to use this file but actually this works so i can grab my settings by using this file ...
