### ISSUE TITLE
ListWafLogs crashes on call the API cant parse logs

### ISSUE THREAD

**Issue by eugsim1** [oracle/oci-go-sdk#203]
Hi team
this calls are crashing :
fmt.Printf("=== waaf logs =======\n" )
 var GetListWafLogsRequest waas.ListWafLogsRequest	 
 for _, k:= range WaasPoliciesResp.Items {
 GetListWafLogsRequest= waas.ListWafLogsRequest {
	   WaasPolicyId : k.Id,
	   }	 
  fmt.Printf("Logs from Policy id:%s\n",  *GetListWafLogsRequest.WaasPolicyId)
  ListWafLogsContent, err := WaasClient.ListWafLogs(context.Background() , GetListWafLogsRequest) 
  if err != nil {
	      fmt.Println("Error WaasClient.ListWafLogs :", err)
	      //return
       }
  for _,l := range ListWafLogsContent.Items {
        fmt.Println("Logs from Policy id:%s\nAction: %s\nUserAgent:%s\n",GetListWafLogsRequest.WaasPolicyId, *l.Action, *l.UserAgent   )   
   }
  }

the logs from the console 👍 

/ | 176.93.194.98 |   | Access | Thu, Nov 28, 2019, 10:52:58 UTC |  
-- | -- | -- | -- | -- | --

the event in JSON

{
  "clientAddress": "176.93.194.98",
  "countryName": "Finland",
  "userAgent": "Go-http-client/2.0",
  "domain": "student0-waf.oraclecloudpursuitlabs.com",
  "httpMethod": "GET",
  "requestUrl": "/",
  "httpHeaders": {
    "Accept-Encoding": "gzip",
    "Host": "student0-waf.ORACLECLOUDPURSUITLABS.COM",
    "User-Agent": "Go-http-client/2.0",
    "X-Client-Ip": "176.93.194.98",
    "X-Country-Code": "FI",
    "X-Forwarded-For": "176.93.194.98"
  },
  "httpVersion": "2.0",
  "referrer": "-",
  "responseCode": 200,
  "responseSize": 1070,
  "incidentKey": "2019-11-28T10:52:58Z|4d7583f67c|176.93.194.98|2bWLPcVI9B",
  "fingerprint": "-",
  "countryCode": "FI",
  "timestamp": "Thu, 28 Nov 2019 10:52:58 GMT",
  "logType": "ACCESS",
  "originAddress": "130.61.61.124:4443",
  "originResponseTime": "0.0120"
}

Error WaasClient.ListWafLogs : parsing time ""Thu, 28 Nov 2019 10:52:58 GMT"" as ""2006-01-02T15:04:05.999999999Z07:00"": cannot parse "Thu, 28 Nov 2019 10:52:58 GMT"" as "2006"

**Comment by jasonyin** [comment]
This is a waas service bug. The date field is not RFC 3339 format.

**Comment by tienpham** [comment]
is there workaround for this issue?

**Comment by jodoglevy** [comment]
We will reach out to the WaaS service team to have them fix this issue

**Comment by tienpham** [comment]
Do you have ETA for this? It's kind of showstopper for us.

**Comment by eugsim1** [comment]
is there a way to skip the date and give the possibility to choose what fields from the records we can collect ?

**Comment by jodoglevy** [comment]
You could use the Go SDK's [raw request signer](https://godoc.org/github.com/oracle/oci-go-sdk#hdr-Signing_Custom_Requests) to make the HTTP request yourself, instead of using the built-in Go SDK ListWafLogs operation for it. The raw request signer won't try to parse the resulting response, and so won't hit the non-RFC-3339 datetime issue

**Comment by eugsim1** [comment]
Hi jodoglevy wiuld be possible to discuss ofline i m internal ? slack ESIMOS
thanks :)

**Comment by eugsim1** [comment]
hi thanks to joe i was thinking that i have workaround the issue ... but i hit another bug from the waaf unrelated to this topic, the raw request is working fine, i m able to "requst" the log of the waaf but for this time the waaf is not logging any more any requests i have opened an SR for the internals SR 3-21809052071thanks
