### ISSUE TITLE
Multipart Download Example

### ISSUE THREAD

**Issue by colt3k** [oracle/oci-go-sdk#204]
Please supply the ability for a multipart download and example from the Object Storage.

**Comment by buzhidao77** [comment]
We currently do not support multipart download from SDK. This is going to be a feature request and we will discuss it within the team.

**Comment by pelliu** [comment]
@colt3k, we added a multipart download example in 43.0.0 release, which you can find here: https://github.com/oracle/oci-go-sdk/blob/master/example/example_objectstorage_multi_download_test.go. I will close this ticket, if any other questions, you can reopen this ticket, or create a new ticket, thanks!
