### ISSUE TITLE
OCI Resource Manager stack is not getting updated with modified variables when created from OCI GO SDK

### ISSUE THREAD

**Issue by PraveenViswanathan** [oracle/oci-go-sdk#206]
HI Team,

I am using "CreateStackRequest" from OCI GO SDK to create a stack but encountering below issue. Once a stack is created and applied in OCI if we do any modifications to the values either directly or using tfvars and update the stack, the changes are not getting reflected. For example. in the attached file we change the node_pool count from 1 to 2. But OCI Stack shows there is no change in the plan and fails to propagate the new changes.

If I upload the same terraform zip file manually using OCI Resource Manager it is working as expected. Requesting you to review the issue and provide your suggestion/fix.

Attachments:

Terraform zip
OCI GO SDK script used to create a stack and launch plan/apply job
Terraform Version : 0.12.x

Thanks.

[ocigosdk.go.zip](https://github.com/oracle/oci-go-sdk/files/3969860/ocigosdk.go.zip)
[stackissue.zip](https://github.com/oracle/oci-go-sdk/files/3969861/stackissue.zip)

**Comment by buzhidao77** [comment]
Working on a fix.

**Comment by buzhidao77** [comment]
@PraveenViswanathan  Could you please send me the complete code snippet? I tried to modify the source code you attached in order to run it but there are still some info missing (e.g. base64Zip function).

**Comment by PraveenViswanathan** [comment]
@buzhidao77 shared the file in your slack

**Comment by buzhidao77** [comment]
Synced up with @PraveenViswanathan 
The ORM stack needs to be updated through UpdateStack API in order for ORM to pick up the new information.

**Comment by buzhidao77** [comment]
@PraveenViswanathan I'm closing this issue as per our discussion. UpdateStack API should be able to get your scenario working.
