### ISSUE TITLE
Downloading a file from Object Storage

### ISSUE THREAD

**Issue by syerabat** [oracle/oci-go-sdk#219]
Hi Jasonyin,
Previous issue: https://github.com/oracle/oci-go-sdk/issues/137

I followed the above fix but I am not able to download the actual file. I am able to get file metadata though. Could you please advise?

Below is my code:

func getObject(ctx context.Context, c objectstorage.ObjectStorageClient, namespace, bucketname, objectname string) error {
request := objectstorage.GetObjectRequest {
NamespaceName: &namespace,
BucketName: &bucketname,
ObjectName: &objectname,
}
out2, err := c.GetObject(ctx, request)
fmt.Println(*out2.ContentMd5) //gets the file md5sum value.
//fmt.Println("out2 value", out2) //Getting file metadata
helpers.FatalIfError(err)
return err
}

**Comment by pelliu** [comment]
Hi @syerabat, is this still an issue for you? I just verified with this example https://github.com/oracle/oci-go-sdk/blob/master/example/example_objectstorage_test.go#L23, and add the following test code 
`	req := objectstorage.GetObjectRequest{
		NamespaceName: &namespace,
		BucketName:    &bname,
		ObjectName:    &filename,
	}
	resp, err := c.GetObject(ctx, req)
	if err == nil {
		fmt.Println(*resp.ContentMd5)
	}`
It works for me, the printed Md5 is `gn7aHPzDTe5Gf3pQcHVOvg==`, Please make sure your object did uploaded to the bucket, otherwise you could get 404 error with error message like:

> "code":"ObjectNotFound","message":"The object 'OCIGOSDKSampleFile839139892' does not exist in bucket 'CjftLJFY' with namespace 'dex-us-phoenix-1'"}
2020/10/22 13:21:57 Service error:ObjectNotFound. The object 'XXXXXXXX' does not exist in bucket 'XXXXXX' with namespace 'XXXXXX'. http status code: 404. Opc request id: XXXXXXXX

**Comment by ZiyaoQiao** [comment]
Hi @syerabat, the file content can be retrieved like this:
```
resp, err := c.GetObject(ctx, request)
helpers.FatalIfError(err)
content, _ := ioutil.ReadAll(resp.Content)
```
Make sure the response is correct before trying to read the content

**Comment by calegari-adriano** [comment]
Hi.
Following the example at: https://docs.oracle.com/en-us/iaas/tools/go-sdk-examples/33.0.0/objectstorage/GetObject.go.html
it works as expected.

But with additional code as @ZiyaoQiao:

> resp, err := c.GetObject(ctx, request)
helpers.FatalIfError(err)
content, _ := ioutil.ReadAll(resp.Content)

if run more than ~ 60 sec to download the object, this throw the error: context deadline exceeded (Client.Timeout or context cancellation while reading body). Less then ~ 60 sec it is ok.

**Comment by ZiyaoQiao** [comment]
Hi,
our client has a timeout configuration set to 60s by default. If your file is relative large, it's better to customize the client configuration with timeout set to 0

**Comment by calegari-adriano** [comment]
Thanks for reply and help.

Following your guess, I did the customization and now works as expected. I saw the code:

// HTTPRequestDispatcher wraps the execution of a http request, it is generally implemented by
// http.Client.Do, but can be customized for testing
type HTTPRequestDispatcher interface {
	Do(req *http.Request) (*http.Response, error)
}

**Comment by pelliu** [comment]
@syerabat and @calegari-adriano , I think it is not an issue for you guys, right? May I close this ticket? Thanks!

**Comment by calegari-adriano** [comment]
+1 right
