### ISSUE TITLE
Document example of creating an anonymous/unauthenticated client

### ISSUE THREAD

**Issue by jlamillan** [oracle/oci-go-sdk#229]
In some cases, it would be helpful to create a client that is unauthenticated. For example, to simply retrieve a list of regions.

It is not clear whether the client can be configured to operate in an unauthenticated mode, and if so, how to do it.

**Comment by jodoglevy** [comment]
Hi @jlamillan - are you sure OCI has APIs that do not require authentication? Can you point me to the docs that mention that / those operations?

**Comment by jlamillan** [comment]
My misunderstanding then.
