### ISSUE TITLE
Example to extract secret

### ISSUE THREAD

**Issue by colt3k** [oracle/oci-go-sdk#235]
Please update examples to include extracting a secret from the vault.

**Comment by ZiyaoQiao** [comment]
Hi, https://docs.oracle.com/en-us/iaas/tools/go-sdk-examples/34.0.0/vault/GetSecret.go.html this is the example for getting the secret from vault. Hope this solves your problem, thanks!

**Comment by ZiyaoQiao** [comment]
Will close this issue, if the example do not work, feel free to reopen this ticket, thanks
