### ISSUE TITLE
Mod Support

### ISSUE THREAD

**Issue by andyday** [oracle/oci-go-sdk#237]
Instead of recommending users use the dep tool, this sdk should fully support go mods and recommend using it for dependencies.

**Comment by pelliu** [comment]
Hi @andyday, thanks for letting us know the requirement, we have provided the support for go mods internally, would you like to try that version first?

**Comment by pelliu** [comment]
Hi @andyday, we have supported Go Mod in v24.0.0, you can find it in https://github.com/oracle/oci-go-sdk/releases/tag/v24.0.0, will close the ticket currently, any other questions, you can reopen it again or create a new ticket, thanks!

**Comment by pelliu** [comment]
Since Go SDK is using major/minor version bump, the go mod feature in Go SDK still has issues, we are working on these issues, so Go Mod feature won't be ready till we can fix them, sorry for the inconvenience.

**Comment by ZiyaoQiao** [comment]
Go SDK supports Go Modules after v25.0.0, you can find it here: https://github.com/oracle/oci-go-sdk/releases/tag/v25.0.0
Please also refer to Readme file to see how to use our latest version with go.mod
