### ISSUE TITLE
Add support for PKCS#8 format API Keys

### ISSUE THREAD

**Issue by scross01** [oracle/oci-go-sdk#242]
The Go SDK only seems to work if the `opc_api_key.pem` is in the PKCS#1 format that begins with the header
```
-----BEGIN RSA PRIVATE KEY-----
```

However I've seen on some systems the `opc_api_key.pem` is created in the PKCS#8 format that begins with the header
```
-----BEGIN PRIVATE KEY-----
```

This 2nd format works fine with the OCI CLI, but fails when using Terraform.  The related code appears to be at:
 
https://github.com/oracle/oci-go-sdk/blob/857a54193bc062afe3933d02b38e3fe9d158f744/common/helpers.go#L233

**Comment by scross01** [comment]
Releted OCI Terraform provider issue https://github.com/terraform-providers/terraform-provider-oci/issues/512

**Comment by pelliu** [comment]
Hi @scross01, thanks for letting us know the requirement, we have added the support for PKCS#8 key format, you can get the feature from latest version `22.0.0`- https://github.com/oracle/oci-go-sdk/releases/tag/v22.0.0
