### ISSUE TITLE
RetryPolicy doesn't work

### ISSUE THREAD

**Issue by tamiraviv** [oracle/oci-go-sdk#266]
Hi,

When you try to do any operation with 'object storage' you can define a field called 'RequestMetadata',
inside this field, you can define another field called RetryPoliy that basically retry your operation the way you define it

Unfortunately, this retry mechanism doesn't work, after the first attempt you will get the following error:

"https://objectstorage.<URL\>: http: ContentLength=XXX with Body length 0"

The problem is that the request body is read to the end on the first call to Do() (https://golang.org/pkg/net/http/#Client.Do), On subsequent calls to Do(), no data is read from the body.

Hope you can fix it soon, Thanks.

____________________________________________________________________________

What I defined:

```golang
requestMetadata := common.RequestMetadata{
		RetryPolicy: &common.RetryPolicy{
			MaximumNumberAttempts: 10,
			ShouldRetryOperation: func(res common.OCIOperationResponse) bool {
				if res.Error != nil {
					return true
				}
				return false
			},
			NextDuration: func(common.OCIOperationResponse) time.Duration {
				return 2 * time.Second
			},
		},
	}
```

What I got:

**Attempt number**: 1
**Error from OCI**: "Service error:TooManyRequests. Too many requests!. http status code: 429. Opc request id: XXX"

**Attempt number**: 2
**Error from OCI**: "Put "https://objectstorage.<URL\>": net/http: HTTP/1.x transport connection broken: http: ContentLength=18051547 with Body length 0"

**Attempt number**: 3
**Error from OCI**: "Put "https://objectstorage.<URL\>": net/http: HTTP/1.x transport connection broken: http: ContentLength=18051547 with Body length 0"

**Attempt number**: 4
**Error from OCI**: "Put "https://objectstorage.<URL\>": net/http: HTTP/1.x transport connection broken: http: ContentLength=18051547 with Body length 0"

and so on ...

**Comment by pelliu** [comment]
Hi @tamiraviv, thanks for letting us know the issue, we will look into the issue and try to fix it ASAP.

**Comment by pelliu** [comment]
Hi @tamiraviv, we have known the root cause of the issue, but it is still being fixing period, not included the change in v32.0.0, will let you know once we can resolve it, thanks for your patients.

**Comment by davejfranco** [comment]
Any update on this?

**Comment by pelliu** [comment]
Hi @tamiraviv and @davejfranco, Go SDK version 40.0.0 fixed retry doesn't work issue when the request body is binary request, but with condition that the request body is resettable request body, which means the request body type should implement seek() method, otherwise we would throw exception that the request doesn't support retry. For detail, please refer the release note. I will currently close the ticket, if any issue hits, we can reopen or create a new ticket.
