### ISSUE TITLE
Oracle OCI Notification Example using Go SDK

### ISSUE THREAD

**Issue by psaini79** [oracle/oci-go-sdk#276]
I am trying to locate the API to call OCI Notification service using go SDK. Is there any example where I can look at the sample to send a slack message or email using Oracle notification service?

**Comment by ZiyaoQiao** [comment]
Hi @psaini79 this the link to `PublishMessage` example: https://docs.oracle.com/en-us/iaas/tools/go-sdk-examples/35.3.0/ons/PublishMessage.go.html for Oracle Notifications related APIs, please check `ons_notificationcontrolplane_clinet` or `one_notificationdataplane_client` under `ons` package. Thanks!

**Comment by pelliu** [comment]
@psaini79, is this still an issue? I found that you'd asked ons service team, if not an issue any more, I will close the ticket, thanks!

**Comment by psaini79** [comment]
The issue is resolved and we should avoid using  MessageType in PublishMessageRequest. Please correct the documentation:  https://docs.oracle.com/en-us/iaas/tools/go-sdk-examples/35.3.0/ons/PublishMessage.go.html.

**Comment by pelliu** [comment]
Thanks, @psaini79, I will work with ons team to resolve it.
