### ISSUE TITLE
documentation about ConfigurationProvider is old

### ISSUE THREAD

**Issue by fabulias** [oracle/oci-go-sdk#277]
Hi, the readme document isn't up to date entirely.

**Current documentation**
```
// ConfigurationProvider wraps information about the account owner
type ConfigurationProvider interface {
   KeyProvider
   TenancyOCID() (string, error)
   UserOCID() (string, error)
   KeyFingerprint() (string, error)
   Region() (string, error)
}
```

**The current code is asking for an `AuthType()` method now.**
```
// ConfigurationProvider wraps information about the account owner
type ConfigurationProvider interface {
	KeyProvider
	TenancyOCID() (string, error)
	UserOCID() (string, error)
	KeyFingerprint() (string, error)
	Region() (string, error)
	// AuthType() is used for specify the needed auth type, like UserPrincipal, InstancePrincipal, etc.
	AuthType() (AuthConfig, error)
}
```

I'll add a PR to fix this when oracle accepts my OCA request.

**Comment by pelliu** [comment]
Hi @fabulias, thanks for your kindly reminder. The readme document will be updated in the next release.

**Comment by fabulias** [comment]
@pelliu could I update that part or isn't necessary?

**Comment by pelliu** [comment]
No, I think I can take care of it, really appreciate it!

**Comment by jodoglevy** [comment]
Let's keep this open for tracking, until the work is done. Peng - I suggest to let Swetha take this one

**Comment by pelliu** [comment]
@fabulias, the doc has updated, again, thanks for the reminder, I will close this ticket. :)

> // ConfigurationProvider wraps information about the account owner
type ConfigurationProvider interface {
   KeyProvider
   TenancyOCID() (string, error)
   UserOCID() (string, error)
   KeyFingerprint() (string, error)
   Region() (string, error)
   // AuthType() is used for specify the needed auth type, like UserPrincipal, InstancePrincipal, etc. AuthConfig is used for getting auth related paras in config file.
   AuthType() (AuthConfig, error)
}
