### ISSUE TITLE
Get instance public IP

### ISSUE THREAD

**Issue by fabioDMFerreira** [oracle/oci-go-sdk#280]
I am not sure how we can get an instance public IP without having to list all public IPs. Does this SDK provide a way to get an instance public IP?

**Comment by fabioDMFerreira** [comment]
found this in docs https://docs.oracle.com/en-us/iaas/Content/Compute/References/oci-public-ip.htm

Only have to figure out which is the method in this SDK.

**Comment by pelliu** [comment]
Hi @fabioDMFerreira, thanks for letting us know your question, if my understanding is correct, you can use our vcn service API `getPublicIP`, which needs the OCID of the public IP, the source code - 
https://github.com/oracle/oci-go-sdk/blob/563148c96ecf546250e48c8cf6527e22e95a9527/core/core_virtualnetwork_client.go#L6422 
and the example - 
https://docs.oracle.com/en-us/iaas/tools/go-sdk-examples/36.1.0/core/GetPublicIp.go.html

**Comment by fabioDMFerreira** [comment]
In my use case, I pretend to get a launched instance public/private IP using the API.

I am getting a list of instances that have the details in this struct https://github.com/oracle/oci-go-sdk/blob/v24.3.0/core/instance.go#L30. From here I'd like to figure out how to get each instance public IP. Not sure how I can do it because the public IP OCID is not in the instance details.

**Comment by pelliu** [comment]
I am not from Compute team or Network team, my understanding, once you can get instance detail, you should be able to get instance ID https://github.com/oracle/oci-go-sdk/blob/v24.3.0/core/instance.go#L40, so use that as the input of the API I showed you(getPublicIP), should get the public IP.

**Comment by fabioDMFerreira** [comment]
I didn't try the get the public IP you suggested. So, should I be able to use the instance ID as the parameter `PublicIpId` (https://github.com/oracle/oci-go-sdk/blob/563148c96ecf546250e48c8cf6527e22e95a9527/core/get_public_ip_request_response.go#L17)?

**Comment by fabioDMFerreira** [comment]
will get back to you once I test it

**Comment by fabioDMFerreira** [comment]
My test didn't work. Probably, `PublicIpId` is reserved for public IPs ids as its own name suggest.

See below what I tried.
```
	client, err := core.NewVirtualNetworkClientWithConfigurationProvider(config)
	fmt.Println(err)

	instanceID := "ocid1.instance.oc1.us-sanjose-1.<...>"

	ip, err := client.GetPublicIp(context.TODO(), core.GetPublicIpRequest{PublicIpId: &instanceID})
	fmt.Println(err)

	fmt.Println(ip)
```

Output
```
<nil>

Service error:NotAuthorizedOrNotFound. Authorization failed or requested resource not found.. http status code: 404. Opc request id: c7ce011794c8f1b3fe63b7b04328219a/8B14446BD04E4024F2BE7E0A6B911698/CCE003043E892EF2811EB633624028FF

{ RawResponse={404 Not Found 404 HTTP/1.1 1 1 map[Content-Length:[111] Content-Type:[application/json] Date:[Tue, 16 Mar 2021 17:04:15 GMT] Opc-Request-Id:[c7ce011794c8f1b3fe63b7b04328219a/8B14446BD04E4024F2BE7E0A6B911698/CCE003043E892EF2811EB633624028FF]] 0xc00021d940 111 [] false false map[] 0xc0001ae400 0xc00012e630} PublicIp={ AssignedEntityId=<nil> AssignedEntityType= AvailabilityDomain=<nil> CompartmentId=<nil> DefinedTags=map[] DisplayName=<nil> FreeformTags=map[] Id=<nil> IpAddress=<nil> LifecycleState= Lifetime= PrivateIpId=<nil> Scope= TimeCreated=<nil> } Etag=<nil> OpcRequestId=c7ce011794c8f1b3fe63b7b04328219a/8B14446BD04E4024F2BE7E0A6B911698/CCE003043E892EF2811EB633624028FF }
```

**Comment by pelliu** [comment]
Would you like to reach out to VCN service team so that you can get help immedately? We have public slack channel #oci_vcn, you can post your question there (you can ask if the API I suggested is the right API to call, if so why get 404, provide them the opc request id...), otherwise we will file a ticket to VCN team, so that they can help you, but maybe slower than that way.

**Comment by fabioDMFerreira** [comment]
No problem. I'll reach them on slack.

**Comment by fabioDMFerreira** [comment]
Could you point me to the slack workspace URL?

**Comment by pelliu** [comment]
@fabioDMFerreira, my bad, seems like our slack channel is not publicly used. I will reach out to VCN team and get back to you.

**Comment by pelliu** [comment]
Hi @fabioDMFerreira, just got confirmation from our VCN team, what @jodoglevy suggested is correct, to query network information, have to start with `vnicattachment` first.

**Comment by fabioDMFerreira** [comment]
Hi @jodoglevy and @pelliu,

That's exactly what I was searching for. Now, I have a way to get the network information of instances using the API. 

It would be nice to get all vnics info (macAddress, Ips, etc) of one instance aggregated in only one response, but certainly, this has architecture implications.

Thanks
