### ISSUE TITLE
ListExternalContainerDatabases LifecycleState: "AVAILABLE" is not working 

### ISSUE THREAD

**Issue by eugsim1** [oracle/oci-go-sdk#284]
Hi 
the filter is not working hte call returns all states i had to add an ugly if see below plese correct :
without the second test if ... AVAILABLE the code return wrong values 
```
req := database.ListExternalContainerDatabasesRequest{
		SortOrder:      database.ListExternalContainerDatabasesSortOrderDesc,
		CompartmentId:  common.String(Comp_ocid),
		LifecycleState: "AVAILABLE",
		SortBy:         database.ListExternalContainerDatabasesSortByDisplayname}
	resp, err := client.ListExternalContainerDatabases(context.Background(), req)
	if err != nil {
		fmt.Printf("err:%s\n", err)
	}
	var LExternalContainerDatabaseSummary []database.ExternalContainerDatabaseSummary 
	for i:=0; i< len(resp.Items); i++ {
	    if (resp.Items[i].LifecycleState == "AVAILABLE") {
		LExternalContainerDatabaseSummary = append(LExternalContainerDatabaseSummary, resp.Items[i])
		utils.Trace.Printf("%s\n",resp.Items[i])
	}}
	return (LExternalContainerDatabaseSummary)
```

**Comment by oci-lm** [comment]
Thanks for reporting this -- we're looking at this and it should be fixed and deployed out by 05/07.

**Comment by oci-lm** [comment]
The fix for this didn't make the last release train - will update when it has been deployed.

**Comment by oci-lm** [comment]
Wasn't able to add an update here for a while, but this issue has been resolved :)

**Comment by jodoglevy** [comment]
Thanks @oci-lm . Closing this issue since it is fixed. @eugsim1 please feel free to reopen this if you are still encountering issues
