### ISSUE TITLE
Unable to locate functions to create dbsystem for BM/RAC/SIDB

### ISSUE THREAD

**Issue by psaini79** [oracle/oci-go-sdk#300]
Hi, I am looking for APIs to create the databases using go sdk as per this link https://docs.oracle.com/en-us/iaas/Content/Database/Concepts/overview.htm.

I am unable to find any example to create the dbsystem for BM/RAC/SIDB using go -sdk.

**Comment by ZiyaoQiao** [comment]
Hi @psaini79 , you can refer to this example: https://github.com/oracle/oci-go-sdk/blob/master/example/example_database_test.go and use LaunchDbSystem function to create dbsystem. Thanks

**Comment by jodoglevy** [comment]
Hi @psaini79 - just following up here since we didn't see a response from you. Did @ZiyaoQiao's response resolve your question?

**Comment by psaini79** [comment]
Yes, it worked and I am able to use go SDK for the DBCS system.
