### ISSUE TITLE
BREAKING CHANGES BETWEEN V40 AND V41 ... 

### ISSUE THREAD

**Issue by eugsim1** [oracle/oci-go-sdk#302]
i had this code working with v40 

   e1 := common.CustomProfileConfigProvider ("./config/config", "oractdemeabdmautodb")
 	
	c, err := identity.NewIdentityClientWithConfigurationProvider(e1)
	if err != nil {
		fmt.Println("Error:", err)
		return
	}

going to v41 +  this code is not working any more 
why there are breaking changes ?

how can we cope ?

**Comment by eugsim1** [comment]
Utils SetConfigProvider oractdemeabdmautodb
utils Tenancy_ocid :ocid1.tenancy.oc1..aaaaaaaa4weq6bgxr4rzg65lzckg2ng2xgglsj2bc5j4n2zngkibwp6i6jza
Utils SetConfigProvider Error: can not create client, bad configuration: open key_file=/home/oracle/.oci/oci_api_key_home.pem: no such file or directory
exit status 1
[oracle@localhost goiam]$ ls -la /home/oracle/.oci/oci_api_key_home.pem
-rw-r--r--. 1 oracle oracle 1679 Nov 20  2020 /home/oracle/.oci/oci_api_key_home.pem

changed the perm still the auth blows !
[oracle@localhost goiam]$ ls -la /home/oracle/.oci/oci_api_key_home.pem
-rw-------. 1 oracle oracle 1679 Nov 20  2020 /home/oracle/.oci/oci_api_key_home.pem
[oracle@localhost goiam]$ go run goiam.go -Tenancy=oractdemeabdmautodb -LoganAction=report
stopInstance stopAutonomous stopDBCS cleanCompartemt true true true true
Utils SetConfigProvider oractdemeabdmautodb
utils Tenancy_ocid :ocid1.tenancy.oc1..aaaaaaaa4weq6bgxr4rzg65lzckg2ng2xgglsj2bc5j4n2zngkibwp6i6jza
Utils SetConfigProvider Error: can not create client, bad configuration: did not find a proper configuration for private key
exit status 1

the first commented line is WORKING WITH V40 but not AFTER THE UPGRADE TO 41+ WHY ?
the second line doenst work neither 

see the code :
	//e1 = common.CustomProfileConfigProvider("./config/config", Provider)
	
	e1 = common.CustomProfileConfigProvider("TF_VAR", "")

**Comment by pelliu** [comment]
@eugsim1, does this still an issue for you? I don't think it is an issue from the Go SDK, after you regenerated the config file, the issue was not there, right? Please let us know if we can close this, thanks!

**Comment by eugsim1** [comment]
Hi i have rotated my keys and now i dont see this issue
