### ISSUE TITLE
Too many requests for the user. http status code: 429.

### ISSUE THREAD

**Issue by fy894684862** [oracle/oci-go-sdk#303]
when I use golang sdk to request oci GetIP interface ,it response "EXTRA common.servicefailure=Service error:TooManyRequests. Too many requests for the user. http status code: 429. Opc request id: 72307bfb6fe68a773c2436db15643244/67D0C5D61EB1EC756BBC778FC74416A3/D9A9385B1666F1595CF5D7AD6632A695)",
how can i find document to learn the threshold value of api call?

**Comment by pelliu** [comment]
@fy894684862 , thanks for letting us know your question, I think different services should have their own criteria for triggering 429 errors, I'm assuming you are asking the vcn service, I will forward the question to them, you can also create an SR from OCI Console to directly ask the service team.

**Comment by pelliu** [comment]
I am not sure if you used Go SDK retry policy, if the answer is yes and got this error, maybe you can consider using different backoff strategy, like exponential backoff, which you can find the reference from our default retry policy https://github.com/oracle/oci-go-sdk/blob/master/common/retry.go#L114.

**Comment by jodoglevy** [comment]
@fy894684862 - just checking in since we haven't heard from you. Did @pelliu's responses resolve your question?

**Comment by jodoglevy** [comment]
@fy894684862 I'm going to close this since we haven't heard back from you, and I think @pelliu's response should resolve your issue. But feel free to reopen this if you are still encountering problems.
