### ISSUE TITLE
Validating Notification signature

### ISSUE THREAD

**Issue by mimol91** [oracle/oci-go-sdk#314]
It would be awesome to have a method that validates the OCI notification signature.
I could not find documentation on how to do it, and after contacting support I've only received snipped of code in Java. (Which I tried to port to go)

I've tried to validate the signature from example that was provided to me but no luck
https://play.golang.org/p/LM5NBGTzkRx

I was able to use OCI SDK to sign and then verify the payload (Unfortunately it does not work with example provided by support)
https://play.golang.org/p/SvQAIiOSsh1

**Comment by jodoglevy** [comment]
Hi @mimol91 - when you say the "OCI notification signature" - can you explain what signature you mean?

Is this related to the [OCI Notifications service](https://docs.oracle.com/en-us/iaas/Content/Notification/Concepts/notificationoverview.htm)? Or do you mean the [API signature sent in any authenticated OCI API request](https://docs.oracle.com/en-us/iaas/Content/API/Concepts/signingrequests.htm#one) (regardless of the OCI service being communicated with)?

**Comment by mimol91** [comment]
Hey @jodoglevy 
I mean https://docs.oracle.com/en-us/iaas/Content/Notification/Concepts/notificationoverview.htm (Notification from OCI to Service, for example about Bucket events, etc)

**Comment by pelliu** [comment]
Hi @mimol91, seems like you are saying common API signature(from the example code you provided), and you want to validate the signature, but may I ask why do you want to validate the OCI API's signature? in my understanding, when you get key pair from OCI, create client for particular OCI service(let's say notification service), and sent the request to the service, service end needs to validate the signature, right? 
When you say support provided you the Java snipped code, did you try it and see if it can work? 
and one more question - "I was able to use OCI SDK to sign and then verify the payload", are you saying previously it works, however, now it doesn't work?

**Comment by mimol91** [comment]
> why do you want to validate the OCI API's signature
To make sure this event is sent via OCI, not any by any 3rd party (Notification is sent to public Webhook endpoint, so anyone can send tampered data). I want to be notified (via Notification - which sends a specific payload to our public webhook endpoint), every time when a file was uploaded to a bucket

> When you say support provided you the Java snipped code, did you try it and see if it can work?

Yes it works

>"I was able to use OCI SDK to sign and then verify the payload", are you saying previously it works, however, now it doesn't work?

It still works, but SKD only allows to sign requests which are being sent **TO** OCI. I need to validate data that is coming (or to be more specific should be coming) **FROM** OCI

**Comment by jodoglevy** [comment]
Thanks @mimol91 - can you provide the Java code you received for validating the signature?

We'll route this to the Notifications team to take a look at

**Comment by mimol91** [comment]
I've wrote on OCI support too, so they might been working on it already
```
package <insert package name here>;

import org.apache.commons.codec.CharEncoding;
import org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider;
import org.junit.BeforeClass;
import org.junit.Test;

import java.io.FileInputStream;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.PublicKey;
import java.security.SecureRandom;
import java.security.Security;
import java.security.Signature;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.util.Base64;

import static org.junit.Assert.assertTrue;

public class VerifyJeddahSignature {

// Get the certificate, this is now publicly available.
// it's in the header parameter: X-OCI-NS-SigningCertURL
// I have stored the cert at this path
private final String certPath = "config/unittest/cacerts/certForSignMessages/jeddah.crt";

@BeforeClass
public static void oneTimeSetup(){
SecureRandom entropySource;
try {
entropySource = SecureRandom.getInstance("NativePRNGNonBlocking", "SUN");
} catch(NoSuchProviderException | NoSuchAlgorithmException e) {
entropySource = new SecureRandom();
}
Security.insertProviderAt(new BouncyCastleFipsProvider(null, entropySource), 1);

}

private boolean verify(String signature, String message) throws Exception {
CertificateFactory fact = CertificateFactory.getInstance("X.509");
FileInputStream is = new FileInputStream (certPath);
X509Certificate cer = (X509Certificate) fact.generateCertificate(is);
PublicKey publicKey = cer.getPublicKey();
MessageDigest messageDigest = MessageDigest.getInstance("SHA-256");
messageDigest.update(message.getBytes(CharEncoding.UTF_8));
byte[] outputDigest = messageDigest.digest();
Signature publicSignature = Signature.getInstance("NONEwithRSA", BouncyCastleFipsProvider.PROVIDER_NAME);
publicSignature.initVerify(publicKey);
publicSignature.update(outputDigest);
byte[] signatureBytes = Base64.getDecoder().decode(signature);
return publicSignature.verify(signatureBytes);

}

@Test
public void testMessageSignatureVerification() throws Exception {
// message body:
// message: KOvteC4lU5iPa7BXqjYelDgmzKv5buK7iyZjDfy9sHzBHe4paPaIeM0Q6YDdGCe4AJAQP6kPEPDZsado46c1Qjd4N88mOIFz542YkqSRXhK7ecVqDvRbwcirRVzZzFw7vPDnoYHgXDdL51OtDtB8QyqycSp0Dtu1zGAwaghVH4zhpVH7jzoC6DefDZZ0dbD19RJNPyZbGFCU1LDQXA0HLdJGKIZsB7PtUaWCTVEj8U5HewTs8oySg1kMQ6bYbuQTRILnvHaHtUzzYZydmCjxvD3ruIxaSJv33ng22epMWiBKEG3xzNnTuid888DjZRHIMnOq06zIJqYQP28V873VWAvC53eLOb1r9aD7osF6lL7UlGSNlSr1NKPIsAEe7Syxq2wmeyoCvxrRH6y4Hag1NwpgyA9PFaRrTR4A0y33T2nNJX3kqj49tvfvA3QAbRtP2yURy0Xi8SeyZ1Nyqw3riicZWGRRuDuzwND3zqdFXnLy5AbTcgH6xqwU9tVxuFWMC4fKwlG0fwfCQUcy10oge9xvNlM0oN458fgejVshV1ebewjimKJw0Whh63AQhpWqWw3MhIPD6fHlu1fiNWIFHSsDANauSWvdryaD0KSuQOgFK65VFvQr3R0BFCPpP4Ahy7RhM8ov0rNI5rCNe6gaYHPEO6tiqxPEXqwP16axQfT2BPVgtRu1ZGNqlkamGcmGMvadWWzQY6mh79Yv0rb0yC7hr54ceTuQsl34VLGJObMKJr0ejM0XitjtYVb0zeYNW1nOShDd6uXDOecCY586xZ06gtT2avpIXoJ8BLmYLiHMqIb6uUyZzZAFhpPp54nahPGVy698x6HUuvfi72rKmfj7ba6MSs9AYhPAYX2u0Y4mZH2IZtgWqGGL7WSTmZ1ZGP8HgS2zWQUquV9ZJOKKiJBqh1hylz82jRi1zKEtiibV61M65oKjR0AlDJeLZDED7kVjngVBF4ZppEOEN2TLHUFnsQfybvggSLKl9naAoPDS5PfypT8BMhDdWMV9Micsb4P2rSM38LP9fBFAEYuPB7SLnef42pI2uXezqqPj2x0DL5UXiEBuwPJvIyrJKoeiGxmHbnZor7fZVbtj8Een2rlmMq3Aw394RshJ7yMixnV1hs7VbU8JpS9CGSa07ocbZTP9195f7BYEQhfehqM2NidExmVlA7lGGJTYMDXMImOWngD5C8MbSDRm7WhozzvNI5QNPqgiMTAZcNJXc0P5aMh1dVL9szCtN6HcwU4c8e8KcHnjyxx1I8Div01nN07iNHuVjwftHZvEqhG3QAdKfn3laDsmT5pM5G2x8xb4DU7tsqW7VaTWldEPmttK9GSde5K8shZuTs02gQaA7UQ9LrMSsMx7iRaC3jgeQgPV3jC3siiaYE8uwN9WQsbIJiOea6nmc8gvmLP9rVDCC86BZnYkgvgUvDMvu4dJZjOC8CtjBkJmsrBgVWeu1bO24RWqVaKZdZsoWwxbwIx26CqGR0Y1XoUkXlrqvoD22IePe9huEXTJAQz8aWFHz2tMN6QnqJbZkzdkBmxY26kOFfd9HpVwslIyviRP8oEm2tJno0AiDekrljJsEKEVxc6xXyenhGEl9t0MqNc7nNNdMoYPHIeikQxuOY8UdsnLMRdylBdzyysEjMqo0MsKToenAQzTf8gv3hcIuulEYQf4nQ9C9Tpga3nLGBJEazXqBMfyv5lA9rzCutO38sZpGI85DGwFwnRuhY56sKRfb6ScbOaBhkK1aN7bqELpHH5ZgTBw3xdqEWQgQj1DieDtTofqakkPh9P96hRAwlN9HyDsIaZpVD5zIjA6BaepXp5MZvT6c09X9RE0mkIM5VI7bdPFms3SH8gQyU1Zb0fl8KD57kYzYbss9n3g7wF2MFpzwjH81L8q4PpBst0AVR2vem647oKIF7jqHJ1B2yiWWz0GC697PrfkN8y0d2pCfAkPa9gxoZaekMispODoYIcC3qgkza9e5URkwB5UN4cDT2yjWclt5sYsErCkdIGLMlMgSbyWvsiGdVXgTrHPQ7mJ8p04cULu

// notificationType: Notification -> from header parameter: X-OCI-NS-MessageType
// messageId: f45256bd-f601-3303-a555-055a5a3445eb -> from header parameter: X-OCI-NS-MessageId
// topicOcid: ocid1.onstopic.oc1.me-jeddah-1.aaaaaaaaubowvycsnzjyswuiaeoweu6g5namzt7vup62xoshhriyxtqml2ba -> from header parameter: X-OCI-NS-TopicOcid
// topicName: CanaryTopic_PublishMsgWithT2Size_8a6dfc46-c6c5-49fe-b4b0-cd446f7195ed -> from header parameter: X-OCI-NS-TopicName
// timeStamp: 2021-05-25T21:58:10.879+0000 -> from header parameter: X-OCI-NS-Timestamp

// OCI notifications signature is signed on the following string:
// strToSign = notificationType + onsMsgEntity.getMessageId() + onsMsgEntity.getTopicId() + onsMsgEntity.getTopicName() + messageBody + timeStamp;

String toSign = "Notification"+"f45256bd-f601-3303-a555-055a5a3445eb"+"ocid1.onstopic.oc1.me-jeddah-1.aaaaaaaaubowvycsnzjyswuiaeoweu6g5namzt7vup62xoshhriyxtqml2ba"+"CanaryTopic_PublishMsgWithT2Size_8a6dfc46-c6c5-49fe-b4b0-cd446f7195ed"+"KOvteC4lU5iPa7BXqjYelDgmzKv5buK7iyZjDfy9sHzBHe4paPaIeM0Q6YDdGCe4AJAQP6kPEPDZsado46c1Qjd4N88mOIFz542YkqSRXhK7ecVqDvRbwcirRVzZzFw7vPDnoYHgXDdL51OtDtB8QyqycSp0Dtu1zGAwaghVH4zhpVH7jzoC6DefDZZ0dbD19RJNPyZbGFCU1LDQXA0HLdJGKIZsB7PtUaWCTVEj8U5HewTs8oySg1kMQ6bYbuQTRILnvHaHtUzzYZydmCjxvD3ruIxaSJv33ng22epMWiBKEG3xzNnTuid888DjZRHIMnOq06zIJqYQP28V873VWAvC53eLOb1r9aD7osF6lL7UlGSNlSr1NKPIsAEe7Syxq2wmeyoCvxrRH6y4Hag1NwpgyA9PFaRrTR4A0y33T2nNJX3kqj49tvfvA3QAbRtP2yURy0Xi8SeyZ1Nyqw3riicZWGRRuDuzwND3zqdFXnLy5AbTcgH6xqwU9tVxuFWMC4fKwlG0fwfCQUcy10oge9xvNlM0oN458fgejVshV1ebewjimKJw0Whh63AQhpWqWw3MhIPD6fHlu1fiNWIFHSsDANauSWvdryaD0KSuQOgFK65VFvQr3R0BFCPpP4Ahy7RhM8ov0rNI5rCNe6gaYHPEO6tiqxPEXqwP16axQfT2BPVgtRu1ZGNqlkamGcmGMvadWWzQY6mh79Yv0rb0yC7hr54ceTuQsl34VLGJObMKJr0ejM0XitjtYVb0zeYNW1nOShDd6uXDOecCY586xZ06gtT2avpIXoJ8BLmYLiHMqIb6uUyZzZAFhpPp54nahPGVy698x6HUuvfi72rKmfj7ba6MSs9AYhPAYX2u0Y4mZH2IZtgWqGGL7WSTmZ1ZGP8HgS2zWQUquV9ZJOKKiJBqh1hylz82jRi1zKEtiibV61M65oKjR0AlDJeLZDED7kVjngVBF4ZppEOEN2TLHUFnsQfybvggSLKl9naAoPDS5PfypT8BMhDdWMV9Micsb4P2rSM38LP9fBFAEYuPB7SLnef42pI2uXezqqPj2x0DL5UXiEBuwPJvIyrJKoeiGxmHbnZor7fZVbtj8Een2rlmMq3Aw394RshJ7yMixnV1hs7VbU8JpS9CGSa07ocbZTP9195f7BYEQhfehqM2NidExmVlA7lGGJTYMDXMImOWngD5C8MbSDRm7WhozzvNI5QNPqgiMTAZcNJXc0P5aMh1dVL9szCtN6HcwU4c8e8KcHnjyxx1I8Div01nN07iNHuVjwftHZvEqhG3QAdKfn3laDsmT5pM5G2x8xb4DU7tsqW7VaTWldEPmttK9GSde5K8shZuTs02gQaA7UQ9LrMSsMx7iRaC3jgeQgPV3jC3siiaYE8uwN9WQsbIJiOea6nmc8gvmLP9rVDCC86BZnYkgvgUvDMvu4dJZjOC8CtjBkJmsrBgVWeu1bO24RWqVaKZdZsoWwxbwIx26CqGR0Y1XoUkXlrqvoD22IePe9huEXTJAQz8aWFHz2tMN6QnqJbZkzdkBmxY26kOFfd9HpVwslIyviRP8oEm2tJno0AiDekrljJsEKEVxc6xXyenhGEl9t0MqNc7nNNdMoYPHIeikQxuOY8UdsnLMRdylBdzyysEjMqo0MsKToenAQzTf8gv3hcIuulEYQf4nQ9C9Tpga3nLGBJEazXqBMfyv5lA9rzCutO38sZpGI85DGwFwnRuhY56sKRfb6ScbOaBhkK1aN7bqELpHH5ZgTBw3xdqEWQgQj1DieDtTofqakkPh9P96hRAwlN9HyDsIaZpVD5zIjA6BaepXp5MZvT6c09X9RE0mkIM5VI7bdPFms3SH8gQyU1Zb0fl8KD57kYzYbss9n3g7wF2MFpzwjH81L8q4PpBst0AVR2vem647oKIF7jqHJ1B2yiWWz0GC697PrfkN8y0d2pCfAkPa9gxoZaekMispODoYIcC3qgkza9e5URkwB5UN4cDT2yjWclt5sYsErCkdIGLMlMgSbyWvsiGdVXgTrHPQ7mJ8p04cULu"+"2021-05-25T21:58:10.879+0000";

// signature send by ONS can be found in header parameter: X-OCI-NS-Signature
// signature: MwrMf6jg2wrgHnbxF6bCNLkn4sBCqAXY9eCNKAvhCXhM2X4D9Id2dmBntOpmIErJCSZV694YxvxXIO6OCxS8yqLqrjY1w6RIL8aR0NA91U87y38ff4adbDhbWnrllFx7A9dXf1jfL1JOFOUtyaITR4eXBdG8MD1942O+0XGGfE//TUd85CuGjpP/QZOi+dXi6ye/3lfNUSVKK6vCiPVeXp6Y5xUmm4M0J39rUXBvl1BV1bcsEgHJXtGIsQaIDNhQfDeW0mdpyA4GPd4eeY1ABhaibp4cUSMufNPH/H6KtXKzEIb/t6qFvT5AwO0II5LxPw+eAxiqklJxzSZgKiWj8A== ->from header parameter: X-OCI-NS-Signature
String signature = "MwrMf6jg2wrgHnbxF6bCNLkn4sBCqAXY9eCNKAvhCXhM2X4D9Id2dmBntOpmIErJCSZV694YxvxXIO6OCxS8yqLqrjY1w6RIL8aR0NA91U87y38ff4adbDhbWnrllFx7A9dXf1jfL1JOFOUtyaITR4eXBdG8MD1942O+0XGGfE//TUd85CuGjpP/QZOi+dXi6ye/3lfNUSVKK6vCiPVeXp6Y5xUmm4M0J39rUXBvl1BV1bcsEgHJXtGIsQaIDNhQfDeW0mdpyA4GPd4eeY1ABhaibp4cUSMufNPH/H6KtXKzEIb/t6qFvT5AwO0II5LxPw+eAxiqklJxzSZgKiWj8A==";
assertTrue(verify(signature, toSign));
}
}
```

**Comment by jodoglevy** [comment]
@mimol91 yes Notifications team mentioned they are working on this with you through a support ticket

**Comment by jodoglevy** [comment]
@mimol91 the Notifications team told me today that your issue should be fixed now. They gave me this as a reference: https://play.golang.org/p/8Fe8P0YVoTg.

Are you ok to close this issue?

**Comment by mimol91** [comment]
oh, so you don't plan to add it to sdk?
OK then, closing. Thanks for help

**Comment by mimol91** [comment]
Unfortunately, Support didn't specify what 'message body' is
HTTP Request body is an JSON
```json
{
  "cloudEventsVersion": "0.1",
  "contentType": "application/json",
  "data": {
    "additionalDetails": {
      "archivalState": "Available",
      "bucketId": "ocid1.bucket.oc1.me-jeddah-1.aaaaaaaaccsdlelmonuvczikcqxpxrnm5xevgw5flo5bpxxf7mnci7eod42q",
      "bucketName": "service-data",
      "eTag": "c1ff03ad-a5cf-48e4-99a7-69f8a072195e",
      "namespace": "axldthpaiqqr",
      "versionId": "c4a7a779-5d54-4b46-b7bb-e0b1450fc7eb"
    },
    "availabilityDomain": "JED-AD-1",
    "compartmentId": "ocid1.tenancy.oc1..aaaaaaaatkzuq2wfvda25q5dir7tq2nhbhaloln5lrq22ljgyq3ie5ukcskq",
    "compartmentName": "someCompany",
    "resourceId": "/n/axldthpaiqqr/b/service-data/o/sau/content/sau_content_address_fields.csv",
    "resourceName": "sau/content/sau_content_address_fields.csv"
  },
  "eventID": "05dbe58c-9eb8-4e5c-8bb7-238f72740b82",
  "eventTime": "2021-09-14T12:37:52Z",
  "eventType": "com.oraclecloud.objectstorage.createobject",
  "eventTypeVersion": "2.0",
  "extensions": {
    "compartmentId": "ocid1.tenancy.oc1..aaaaaaaatkzuq2wfvda25q5dir7tq2nhbhaloln5lrq22ljgyq3ie5ukcskq"
  },
  "source": "ObjectStorage"
}
```
I've tried to use this whole HTTP body as a 'message body', but it didn't get validated correctly.
Could you please advise how to get a 'message body' from an HTTP request

**Comment by jodoglevy** [comment]
I'll ask Notifications team to respond here

**Comment by maheshwarigagan** [comment]
@mimol91 Can you please share the whole object you received from ONS? with headers and body

**Comment by mimol91** [comment]
curl --request POST \
  --url http://127.0.0.1:9090/webhooks/oci/notification \
  --header 'accept: */*' \
  --header 'connection: close' \
  --header 'content-type: application/json' \
  --header 'user-agent: Apache-HttpAsyncClient/4.1.4 (Java/1.8.0_162)' \
  --header 'x-oci-ns-messageid: e2a3fb1f-f397-ac5d-a835-955a167827ec' \
  --header 'x-oci-ns-messagetype: Notification' \
  --header 'x-oci-ns-signature: lsRo74bI5bfGoxLrL+sSdc4mThNglCNDBRzY07BqPHMbPtk/rwFpI81EPVALeK29lpQpSYqx6AkenoO99IrS7OO0nH7DP76Jv+bHhzRJ8N0eVJO3rnSdoxJHJSJs3EgoXVaDkv9mUseGAEf/LQixgL1eQKgCzyPhDXraGRGwFttoTtoKCJbTXUUv0rqhSwn3j0yZR3mvzD9/I5UyWz55c8lh25zshss9ZhOUnhDuM4nDgOcquoZjvji2OzWe9IuCqmu41bN6rr7iuC7Mz8umafef4OvUg6zsZ3SvMypd8lz/ap65FlyGMvWqXNaoPaV/pk7nq8/qTaYvyU6+khs8DQ==' \
  --header 'x-oci-ns-signatureversion: 2.0' \
  --header 'x-oci-ns-signingcerturl: https://objectstorage.me-jeddah-1.oraclecloud.com/p/O0gkp5I0MtGhZAmqEj_U90DYCgsiHU3nsIuNBYlLaRRczvSKoJL_7XEtZdyfCD-8/n/bmc-ons-prod/b/ons-ds/o/ds-signature-public-certificate-jeddah.crt' \
  --header 'x-oci-ns-timestamp: 2021-09-14T12:38:00.774+0000' \
  --header 'x-oci-ns-topicname: CreateObject' \
  --header 'x-oci-ns-topicocid: ocid1.onstopic.oc1.me-jeddah-1.aaaaaaaa4py7dbhsvl4m5m62vdbypglzwpidys6iqcihnu7mmyy5h6sddica' \
  --data '{
  "cloudEventsVersion": "0.1",
  "contentType": "application/json",
  "data": {
    "additionalDetails": {
      "archivalState": "Available",
      "bucketId": "ocid1.bucket.oc1.me-jeddah-1.aaaaaaaaccsdlelmonuvczikcqxpxrnm5xevgw5flo5bpxxf7mnci7eod42q",
      "bucketName": "wahed-service-data",
      "eTag": "c1ff03ad-a5cf-48e4-99a7-69f8a072195e",
      "namespace": "axldthpaiqqr",
      "versionId": "c4a7a779-5d54-4b46-b7bb-e0b1450fc7eb"
    },
    "availabilityDomain": "JED-AD-1",
    "compartmentId": "ocid1.tenancy.oc1..aaaaaaaatkzuq2wfvda25q5dir7tq2nhbhaloln5lrq22ljgyq3ie5ukcskq",
    "compartmentName": "wahedtech",
    "resourceId": "/n/axldthpaiqqr/b/wahed-service-data/o/sau/content/sau_content_address_fields.csv",
    "resourceName": "sau/content/sau_content_address_fields.csv"
  },
  "eventID": "05dbe58c-9eb8-4e5c-8bb7-238f72740b82",
  "eventTime": "2021-09-14T12:37:52Z",
  "eventType": "com.oraclecloud.objectstorage.createobject",
  "eventTypeVersion": "2.0",
  "extensions": {
    "compartmentId": "ocid1.tenancy.oc1..aaaaaaaatkzuq2wfvda25q5dir7tq2nhbhaloln5lrq22ljgyq3ie5ukcskq"
  },
  "source": "ObjectStorage"
}'

**Comment by mimol91** [comment]
@maheshwarigagan Any up-dates?

**Comment by mimol91** [comment]
It seems that I had some typo. I've tried again and it's validating payload correctly. Sorry for confusion
