### ISSUE TITLE
extract secret content vault

### ISSUE THREAD

**Issue by joaqquin89** [oracle/oci-go-sdk#324]
Guys 

i have a big problem , because i want to extract the secret content (i have the secret in the vault oci) ... i am trying to use this api and this example https://docs.oracle.com/en-us/iaas/tools/go-sdk-examples/49.0.0/vault/GetSecret.go.html but that example only get the secret characteristics ... not the secret content

**Comment by moolen** [comment]
As far as i can tell the API is split into a two APIs: `Vault Secret Management` and `Vault Secret Retrieval`. This SDK splits it into two packages `vault` (for management) and `secrets` (for retrieval). Take a look [here](https://github.com/oracle/oci-go-sdk/blob/378239d6f32bd6bf2441c09fda48b10b33836bf5/secrets/secrets_client.go#L125), using `secrets.GetSecretBundle()` should work for your use-case.

**Comment by alexdyas** [comment]
Interesting, I came across the same confusion using the Python SDK, took me a good while to figure it out.

**Comment by jodoglevy** [comment]
Since we haven't heard back from the original issue reporter in over a month, and it seems like the answer has been provided by @moolen (thanks @moolen!), I'm going to close this issue. However, if this is not actually resolved, please feel free to reopen.
