### ISSUE TITLE
RestoreAutonomousDatabase returns InvalidParameter 

### ISSUE THREAD

**Issue by harayuanwang** [oracle/oci-go-sdk#330]
Hi Folks,

I got {"code" : "InvalidParameter",  "message" : "Unable to process JSON input"} when I executed [the example](https://docs.cloud.oracle.com/en-us/iaas/tools/go-sdk-examples/latest/database/RestoreAutonomousDatabase.go.html).
The timestamp in the json request body seems invalid.
The request body after the marshling: `"timestamp": "2021-11-12T13:10:34.436873-05:00"`,
which supposed to be `"timestamp": "2021-11-12T13:10:34.436Z"`

**Comment by jodoglevy** [comment]
@harayuanwang  this seems like an issue with the Database service not respecting the RFC3339Nano timestamp specification on this operation. I will route this to the Database team to take a look

**Comment by jodoglevy** [comment]
@harayuanwang I talked to the Database team, they are working on a fix for this and expect it to be ready soon

**Comment by harayuanwang** [comment]
@jodoglevy Thanks for the update. Is there an ETA or a pointer to know when the fix is ready?

**Comment by jodoglevy** [comment]
@harayuanwang - this should be available by end of the month

**Comment by jodoglevy** [comment]
@harayuanwang  can you check if this issue is now resolved?

**Comment by harayuanwang** [comment]
@jodoglevy the issue has been verified as resolved. Thanks for the help!
