### ISSUE TITLE
List API call for object storage bucket objects does not return all values

### ISSUE THREAD

**Issue by c0d3r-arnab** [oracle/oci-go-sdk#336]
The list API call for object storage bucket objects does not return all the values mentioned in the structure. Attributes like `Size`, `Md5`, `TimeCreated` etc. are coming as null. Following is the log of the response that we received:
```
objectSummary="{ Name=test-obj-1object.txt Size=<nil> Md5=<nil> TimeCreated=<nil> Etag=<nil> StorageTier= ArchivalState= TimeModified=<nil> }"
```

The CLI command for the list call returns all the data.
```
oci os object list --bucket-name test-buket
{
  "data": [
    {
      "archival-state": null,
      "etag": "33b2e007-e72e-45b9-be52-979135e9cf72",
      "md5": "Q9MZB7Gof0gwLmQxy7eC8g==",
      "name": "test-obj-1object.txt",
      "size": 517,
      "storage-tier": "Standard",
      "time-created": "2022-01-06T08:54:09.154000+00:00",
      "time-modified": "2022-01-06T08:54:09.154000+00:00"
    }
  ],
  "prefixes": []
}
```

I have also noticed that the response structures of the GET and List API calls are different. There are attributes in the List API response structure, e.g. `TimeCreated`, that are missing in the GET API response structure and vice versa.

SDK version used: v44.0.0

I will appreciate some insight on this matter. Please let me know if you will need any additional information.

**Comment by jodoglevy** [comment]
@c0d3r-arnab  there is a `fields` parameter you need to set in the request, to say what additional fields you'd like returned by this API. Please use that parameter if you'd like size, md5, timeCreated, etc, included.

**Comment by jodoglevy** [comment]
See https://github.com/oracle/oci-go-sdk/issues/123 for more info

**Comment by c0d3r-arnab** [comment]
It worked for me. Thank you for the reference.
