### ISSUE TITLE
With latest version 57.0.0 Data Source status are not case-insensitive anymore

### ISSUE THREAD

**Issue by auriben** [oracle/oci-go-sdk#343]
Hi, we are having our TF code broken as we are getting the following error while validating the status of a Data Source, a VCN in this example

```
│ Error: unsupported enum value for LifecycleState: Available. Supported values are: PROVISIONING,AVAILABLE,TERMINATING,TERMINATED,UPDATING.
│
│ with module.vcn_corpdev.data.oci_core_vcns.vcns,
│ on ../terraform/modules/vcn_data/vcn_data.tf line 1, in data "oci_core_vcns" "vcns":
│ 1: data "oci_core_vcns" "vcns" {
```
Documentation states that those values are case insensitive https://registry.terraform.io/providers/hashicorp/oci/latest/docs/data-sources/core_vcns which is not the case now

Can you please take a look to this issue, also please refer https://github.com/terraform-providers/terraform-provider-oci/issues/1528 for the same issue

Thank you!

**Comment by ZiyaoQiao** [comment]
Thanks @auriben  we'll discuss with TF team to find a solution to this

**Comment by auriben** [comment]
Refer https://github.com/terraform-providers/terraform-provider-oci/issues/1528 for the impact of this as well

**Comment by ZiyaoQiao** [comment]
Hi @auriben in version v58.0.0, we made the changes to perform case-insensitive enum value validation in go SDK. Terraform will release a new version soon to include this change. Please upgrade your terraform version after they release and try again? Thanks!

**Comment by auriben** [comment]
Thank you @ZiyaoQiao for following up on this!

**Comment by auriben** [comment]
I have pulled v4.64.0 of hashicorp/oci which contains SDK v58.0.0 and now I can confirmed this issue is fixed, thank you!

**Comment by jotruon** [comment]
You should use Terraform provider version v4.62.0 or move up to v4.64.0 to avoid this error
