### ISSUE TITLE
Option to override the default logger

### ISSUE THREAD

**Issue by eljasala** [oracle/oci-go-sdk#356]
Currently the only way to control logging in OCI Go SDK is to use the environment variables (OCI_GO_SDK_DEBUG, OCI_GO_SDK_LOG_OUTPUT_MODE, OCI_GO_SDK_LOG_FILE). This results in at least following limitations:
1) OCI Go SDK logging cannot be enabled in OCI Functions at least easily
2) The only way to customize logging would be to write things to file and follow the file(s) in the custom code or maintain custom fork that customizes the log.go. These customization could be e.g. changing all output to JSON, adding some context to the log message or sending the log somewhere else.

At minimum this would require making setSDKLogger public https://github.com/oracle/oci-go-sdk/blob/master/common/log.go#L59 & possibly sdkLogger interface as well https://github.com/oracle/oci-go-sdk/blob/master/common/log.go#L18
Other alternative would be to allow passing custom logger to e.g. configuration provider, but that's likely quite a bit more effort as defaultLogger seems to be used directly by some parts of the code. It might also make tricky to add support for logging before configuration provider is initialized (e.g. auth.InstancePrincipalConfigurationProvider() does call the logging).

**Comment by ZiyaoQiao** [comment]
Thanks so much for sharing this. We'll discuss the solution for this

**Comment by swkrkris** [comment]
The solution for this will be part of June 7 release

**Comment by eljasala** [comment]
Thank you, it looks like SetSDKLogger was made public.
https://github.com/oracle/oci-go-sdk/commit/31171be112f8d49071c72e8c352d5e7a6a4b903c#diff-326549de57835812e50d36524254fb6770f448d3f521026f0b09fa97201306aaR58-R64
