### ISSUE TITLE
All fault domains details does not come for MySQL DB systems with High Availability

### ISSUE THREAD

**Issue by bigdatasourav** [oracle/oci-go-sdk#371]
We have configured MySQL DB systems for High Availability; hence, it is deployed under multi-fault domain architecture. But the below APIs do not provide details of all the fault domains. It only provides information about the preferred one.
https://pkg.go.dev/github.com/oracle/oci-go-sdk/v44@v44.0.0/mysql#DbSystemClient.ListDbSystems
https://pkg.go.dev/github.com/oracle/oci-go-sdk/v44@v44.0.0/mysql#DbSystemClient.GetDbSystem

**Comment by KartikShrikantHegde** [comment]
Hi @bigdatasourav ,

Thanks for reporting the issue. We will ask the relevant team to take a look and provide an update.

**Comment by bigdatasourav** [comment]
Hey @KartikShrikantHegde, Could you please provide an update regarding the above?

**Comment by KartikShrikantHegde** [comment]
Hi @bigdatasourav ,

Do you have a Customer Support Identifier (CSI) number that you can share with us? That would help us get traction fast.

Thanks.

**Comment by jsled-at-oracle** [comment]
This is as designed.

The Availablity Domains and Fault Domains for a given region can be accessed through the [`ListAvailabilityDomains`](https://pkg.go.dev/github.com/oracle/oci-go-sdk/v44@v44.0.0/identity#IdentityClient.ListAvailabilityDomains) and [`ListFaultDomains`](https://pkg.go.dev/github.com/oracle/oci-go-sdk/v44@v44.0.0/identity#IdentityClient.ListFaultDomains) operations on the `identity` module.

The ListDbSystem and GetDbSystem APIs here do return both the user-specified "preferred" placement (in `availabilityDomain` and `faultDomain`), and the `currentPlacement` of the DBSystem.
