### ISSUE TITLE
cannot build on js/wasm, plan9/386, plan9/amd64, solaris/amd64

### ISSUE THREAD

**Issue by msays2000** [oracle/oci-go-sdk#384]
Related issue on dependent package: https://github.com/gofrs/flock/issues/60

used in code: https://github.com/oracle/oci-go-sdk/blob/master/common/eventual_consistency.go#L96
can we use something else simpler...than this package

## github.com/gofrs/flock plan9/386 
../../../../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:28:30: undefined: syscall.LOCK_EX
../../../../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:39:30: undefined: syscall.LOCK_SH
../../../../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:57:20: undefined: syscall.Flock
../../../../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:67:20: undefined: syscall.Flock
../../../../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:97:20: undefined: syscall.Flock
../../../../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:97:50: undefined: syscall.LOCK_UN
../../../../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:119:29: undefined: syscall.LOCK_EX
../../../../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:131:29: undefined: syscall.LOCK_SH
../../../../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:151:17: undefined: syscall.Flock
../../../../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:151:52: undefined: syscall.LOCK_NB
../../../../go/pkg/mod/github.com/gofrs/flock@v0.8.1/flock_unix.go:151:52: too many errors
2022/09/06 23:09:27 ----------------------------
2022/09/06 23:09:27 Error compiling plan9/386: exit status 2

**Comment by KartikShrikantHegde** [comment]
Hi @msays2000,

Thanks for reporting the issue. Our team will take a look and get back to you.

**Comment by swkrkris** [comment]
Hi @msays2000,

I am looking to see if there are other viable alternatives. 
In the mean time can you please let us know how you are building.

**Comment by swkrkris** [comment]
Hi @msays2000 , Did you get a chance to look into this ticket. Can you please let us know how you are building.

**Comment by msays2000** [comment]
hi @swkrkris **you may close this ticket as won't supported on above platforms** if needed, I am not blocked. the oci sdk compilation is failing due to the third party package that is used doesn't compile on those platforms. 

you can build the cross compile the sdk to see the failures.

GOOS=target-OS GOARCH=target-architecture go build ... 
example:
GOOS=plan9 GOARCH=amd64 go build ... 
 failing combinations are: js/wasm, plan9/386, plan9/amd64, solaris/amd64
 all valid combinations are listed in https://go.dev/doc/install/source

$GOOS | $GOARCH
-- | --
  | aix | ppc64
  | android | 386
  | android | amd64
  | android | arm
  | android | arm64
  | darwin | amd64
  | darwin | arm64
  | dragonfly | amd64
  | freebsd | 386
  | freebsd | amd64
  | freebsd | arm
  | illumos | amd64
  | ios | arm64
  | js | wasm
  | linux | 386
  | linux | amd64
  | linux | arm
  | linux | arm64
  | linux | loong64
  | linux | mips
  | linux | mipsle
  | linux | mips64
  | linux | mips64le
  | linux | ppc64
  | linux | ppc64le
  | linux | riscv64
  | linux | s390x
  | netbsd | 386
  | netbsd | amd64
  | netbsd | arm
  | openbsd | 386
  | openbsd | amd64
  | openbsd | arm
  | openbsd | arm64
  | plan9 | 386
  | plan9 | amd64
  | plan9 | arm
  | solaris | amd64
  | windows | 386
  | windows | amd64
  | windows | arm
  | windows | arm64

**Comment by swkrkris** [comment]
Closing this ticket
