### ISSUE TITLE
unable to create IAM resources in secondary domain.

### ISSUE THREAD

**Issue by aaps3579** [oracle/oci-go-sdk#388]
Is there any support in OCI SDK/REST API for creating iam resources(users, groups, policies) in the secondary domain ?
I have been trying to configure the [identity client](https://github.com/oracle/oci-go-sdk/blob/v65.21.0/identity/identity_client.go#L22) host field to the secondary domain IDCS url but got look up failed error.
```
dial tcp: lookup idcs-xxx.us-ashburn-1.oraclecloud.com: no such host
```

**Comment by KartikShrikantHegde** [comment]
Hi @aaps3579 ,

We will check with the Identity team and get back to you.

**Comment by manojkgaddam** [comment]
Hi @aaps3579 secondary domains are not supported in OCI SDK yet. But you can use REST APIs for managing resources in those domains. API documentation is at https://docs.oracle.com/en/cloud/paas/iam-domains-rest-api/index.html. 

You would use the IDCS GUID (idcs-xxxx) in the URLs this way: idcs-xxx.identity.oraclecloud.com/admin/v1/<resource>. For example, POST idcs-xxx.identity.oraclecloud.com/admin/v1/Users to create users in the domain.

**Comment by aaps3579** [comment]
Thanks for reply @manojkgaddam. I was able to create IAM resources using API with secondary domain's IDCS url.
