### ISSUE TITLE
ListAutonomousDatabases API doesn't return CMK Encryption Info

### ISSUE THREAD

**Issue by ParthaI** [oracle/oci-go-sdk#397]
**Bug Details**

Dear team,
- We have an Autonomous Database with CMK encryption on our console, and we're trying to access the resource details via the API  [ListAutonomousDatabases](https://pkg.go.dev/github.com/oracle/oci-go-sdk/v44@v44.0.0/database#DatabaseClient.ListAutonomousDatabases).
- However we are getting the other details except the encryption properties like KmsKeyId, VaultId, KmsKeyLifecycleDetails, KmsKeyVersionId, KeyStoreId and KeyStoreWalletName.

Could you please have an attention to this issue?
If you need anything else please let me know.

Thanks!
Partha

#
**Current Behaviour**
The API  [ListAutonomousDatabases](https://pkg.go.dev/github.com/oracle/oci-go-sdk/v44@v44.0.0/database#DatabaseClient.ListAutonomousDatabases) does not provide information about encryption details.

#
**Expected Behaviour**
We should able to get KmsKeyId, VaultId, KmsKeyLifecycleDetails, KmsKeyVersionId, KeyStoreId and KeyStoreWalletName details for an Autonomous Database.

**Comment by KartikShrikantHegde** [comment]
Thank you for reporting the issue. We will ask the Autonomous Database team to take a look.

**Comment by ParthaI** [comment]
Hi @KartikShrikantHegde, do you have any update for this issue?

**Comment by KartikShrikantHegde** [comment]
Hi @ParthaI Database team had a chance to take a look at this - the database can be configured to use the KMSKeyId and VaultId. Once the database is configured, KMSKeyId and VaultId are part of the response for both the Get and List Autonomous Database APIs.

But you will have to use KMS Service APIs to pull KMS-related information such as KmsKeyLifecycleDetails, KmsKeyVersionId, KeyStoreId, and KeyStoreWalletName. Database Service does not maintain that information or attributes.

**Comment by KartikShrikantHegde** [comment]
Hi @ParthaI , I will close this ticket, please feel free to re-open it if you still have issues. Thanks!
