### ISSUE TITLE
Option to query vault secrets by name

### ISSUE THREAD

**Issue by leangaurav** [oracle/oci-go-sdk#399]
I see this option available in java sdk
https://blogs.oracle.com/cloudsecurity/post/manage-secrets-by-name-in-oci

And also part of CLI, so should be available in python sdk  also. Please add this in go sdk also.

**Comment by code-dudes** [comment]
Hi @KartikShrikantHegde 

Thanks a lot for pointing to the right docs. Reaching this doc seems to be tough. I was trying to look into the go vault sdk source code for any option to get secrets by name. But it seems to be in a different package.

This should work. Thanks again.
