### ISSUE TITLE
Oracle graph database with golang drivers and sdk

### ISSUE THREAD

**Issue by chaudharisuresh997** [oracle/oci-go-sdk#403]
Hi
I want to use oracle graph database but i cannot find any graph db sdk for golang
can you please share examples and sdk link for golang

**Comment by agodfrind** [comment]
Can you clarify what you mean by _use oracle graph database_? Do you mean the **Oracle Graph Client and Server** product (like https://www.oracle.com/database/technologies/spatialandgraph/property-graph-features/graph-server-and-client/graph-server-and-client-downloads.html) ?

The main architecture of this product is a **graph server:** a REST-enabled web application that you use to **load graphs in memory** (from an Oracle database) and perform **graph analytics** on those graphs: run well-known **graph algorithms** or do graph traversal using the **PGQL** language.

All those operations are available via a core **java** API. We also offer a **python** API (that essentially layers on top of the java API). And we also offer direct access to the **REST** API, used by the java API.

At present we do not offer any specific API for the GO language.

**Comment by agodfrind** [comment]
The discussions here for the **oci-g-sdk**, an SDK that allows you to manage OCI resources (databases, compute instances, object store and much more) using the GO language. It is not about using the GO language with generic Oracle offerings (like the Oracle Database or its extensions).

Let me still try and answer your question.

Can you clarify what you mean by _use oracle graph database_ ? Do you mean the **[Oracle Graph Client and Server](https://www.oracle.com/database/technologies/spatialandgraph/property-graph-features/graph-server-and-client/graph-server-and-client-downloads.html)** product ?

The main architecture of this product is a graph server: a **REST-enabled** web application that you use to **load graphs** in memory (from an Oracle database) and perform **graph analytics** on those graphs: run well-known graph **algorithms** or do graph **traversal** using the **PGQL** language.

All those operations are available via a core **java** API. We also offer a **python** API (that essentially layers on top of the java API). At present we do not offer any specific API for the GO language. For this and other languages (C#, ...) we offer direct access via the **REST API**.

About Oracle Cloud solutions, we also offer Graph as an extension to Autonomous Databases as **[Graph Studio](https://docs.oracle.com/en/cloud/paas/autonomous-database/graph-studio.html)**. This fully-managed environment takes care automatically about starting and managing the Graph Server. It helps designing graphs from relational data, and also offers a set of **notebooks** to use the graphs and interact with them visually. Accessing the graph server is possible from applications just like explained above: java, python or REST.

**Comment by jodoglevy** [comment]
@chaudharisuresh997 - we haven't heard from you in a couple weeks here. Does the info from @agodfrind answer your questions? Can this issue be closed?

**Comment by jodoglevy** [comment]
Closing this as we haven't heard back from the reporter in multiple weeks
