### ISSUE TITLE
Support creating and managing users and groups within an identity domain

### ISSUE THREAD

**Issue by F21** [oracle/oci-go-sdk#411]
The SDK supports creating and managing the lifecycle of identity domains, but there is currently no way to add or manage users and groups within a specific identity domain.

I believe this needs to be implemented in the OCI API first before it can be implemented in the SDK. For example, the documentation for creating and managing users does not offer any options to put the user in a specific identity domain: https://docs.oracle.com/en-us/iaas/api/#/en/identity/20160918/User/CreateUser

I think this is a rather important addition to the API as it would allow identity domains to be completely managed using the terraform provider.

References:
- https://github.com/oracle/terraform-provider-oci/issues/1684
- https://github.com/oracle/terraform-provider-oci/issues/1526
- https://github.com/oracle/terraform-provider-oci/issues/1631

**Comment by manojkgaddam** [comment]
You should use [Identity Domains REST APIs](https://docs.oracle.com/en/cloud/paas/iam-domains-rest-api/index.html) to manage resources in Identity Domains. We are working on adding support for these APIs in OCI SDK clients & Terraform provider.

**Comment by KartikShrikantHegde** [comment]
Hi @F21 , does the above answer help? If so I will close this ticket. Let us know. Thanks!

**Comment by manojkgaddam** [comment]
Hi @F21, we just released the Go SDK with support for managing users & groups in identity domains ([v65.32.1](https://github.com/oracle/oci-go-sdk/releases/tag/v65.32.1)). You can also find links to the latest versions of other language clients and Terraform provider on docs.oracle.com
