### ISSUE TITLE
OCID doesn't match expected pattern or contains invalid characters.

### ISSUE THREAD

**Issue by retrofit2** [oracle/oci-go-sdk#414]
OCID doesn't match expected pattern or contains invalid characters. . http status code: 400. Opc request id: bom-1:BKpwyX82i3zARx4YrD3UoNiK80WOCL5BXhNYfZD93CvbqiB8NWEPuN2Q0jFPQM

Hi, I'm going to use Object Storage with example https://github.com/oracle/oci-go-sdk/blob/master/example/example_objectstorage_test.go

go version: go1.18.10 linux/amd64

what i'm tyring to is below before using sdk

1. make new IDCS user in new group that assined policy with all grant in some compartment.

2. create the user's oci_api_key.pem and oci_api_key_public.pem at oci console.

3. copy config, oci_api_key.pem(private key) to ~/.oci and command chmod as instruction 

4. finally go run main.go

OCID doesn't match expected pattern or contains invalid characters. . http status code: 400. Opc request id: bom-1:BKpwyX82i3zARx4YrD3UoNiK80OCL5BXhNYfZD93CvbqiB8NWEPuN2Q0jFPQM

that error placed where the func createBucket(ctx, c, namespace, bname) called in
func ExampleObjectStorage_UploadFile()

but removing the func createBucket() and deleteBucket(),
and create bucket myself at console,
then the object was created.

why does not bucket created?

**Comment by KartikShrikantHegde** [comment]
Hello, our team will take a look, thanks for reporting.

**Comment by jodoglevy** [comment]
@retrofit2 what values did you pass for the parameters of createBucket?

**Comment by retrofit2** [comment]
@jodoglevy I'm not modify that example, so parameters are ctx, c, namespace, bname(random 8-character as string).

my ~/.oci path contains 2 file -> config, oci_api_key.pem (that is private-key)

config has 

[DEFAULT]
user=ocid1.user.oc1..aaaaaaaaSOME_STRING
fingerprint=SOME_FINGER_PRINT
tenancy=ocid1.tenancy.oc1..aaaaaaaaSOME_STRING
region=ap-SOME_REGION
key_file=~/.oci/oci_api_key.pem

**Comment by jodoglevy** [comment]
@retrofit2  thanks. did you modify the config file above to obfuscate values, or is that literally the contents of your config file? For example, for the `user` value do you have `ocid1.user.oc1..aaaaaaaaSOME_STRING` as the exact value in your config file? If so, these values look incorrect -- you need to fill in the correct values for each parameter, in the config file, for your tenancy.

Even if you did not modify the example file, can you modify it to spit out the values its passing for namespace and bucket name? I would like to validate if those values look ok or not.

**Comment by retrofit2** [comment]
@jodoglevy 

the value like SOME_STRING is NOT a real value in my config file.
i just tell you for example.
the config file in my `.oci` folder is copied from
`oracle cloud console -> Identity -> Users -> UserDetails -> API Keys -> View Configuration file`.
I changed the file only `key_file=<path to your private keyfile> # TODO` part.

i think if the value passed in config is not valid, perhaps PutObject() was not working, but it worked.
do you mean that i could write my config file's `user` full value? i don't understand

1. namespace prints right in my vscode terminal as seen at browser console on command go run main.go.
    (It works)
2. bucket name is a random string as sdk example's example_objectstorage_test.go file.
   (it doesnt' work but I created bucket manually, removing createBucket() on the example code, object is created in manually created bucket)

**Comment by jodoglevy** [comment]
@retrofit2 if that same config file works for the PutObject operation, yes, the config file seems like it is fine, in that case.

The problem is most likely in the bucket name value being passed to CreateBucket. If you, instead of using a random string value, pick a value with only letters and numbers, such as `foobar123`, for the bucket name for the bucket to create, does the code execute successfully and the bucket get created?

**Comment by retrofit2** [comment]
@jodoglevy  it also doesn't work

```
	c, clerr := objectstorage.NewObjectStorageClientWithConfigurationProvider(common.DefaultConfigProvider())
	helpers.FatalIfError(clerr)

	ctx := context.Background()
	bname := "foobar123"
	namespace := getNamespace(ctx, c)

	createBucket(ctx, c, namespace, bname)
	defer deleteBucket(ctx, c, namespace, bname)
```

Service error:BadRequest. OCID doesn't match expected pattern or contains invalid characters. . http status code: 400. Opc request id: bom-1:NDraAG31UMM23RgRrqi1lsXr9Lof_y88vFnihFO7EtuS0s5toWYhJSKOonXdmXu

**Comment by jodoglevy** [comment]
@retrofit2 - hmm, that is certainly strange. what if you set the namespace to some other value like `abc123`, just for testing purposes? What error do you get back from the createBucket call -- same error as before, or a different errror?

**Comment by retrofit2** [comment]
Same error as before 😭


Service error:BadRequest. OCID doesn't match expected pattern or contains invalid characters. . http status code: 400. Opc request id: bom-1:COOQCl1oD-ZD9VZLXnz4CNWxSoncN88sajoiWJxDbbpPLs9QN03LuwtMT73u

``` 
func ExampleObjectStorage_UploadFile() {
	c, clerr := objectstorage.NewObjectStorageClientWithConfigurationProvider(common.DefaultConfigProvider())
	helpers.FatalIfError(clerr)

	ctx := context.Background()
	bname := "foobar123"
	namespace := "abc123"

	createBucket(ctx, c, namespace, bname)
	defer deleteBucket(ctx, c, namespace, bname)

        ....
}

```

```
func createBucket(ctx context.Context, c objectstorage.ObjectStorageClient, namespace, name string) {
	request := objectstorage.CreateBucketRequest{
		NamespaceName: &namespace,
	}
	request.CompartmentId = helpers.CompartmentID()
	request.Name = &name
	request.Metadata = make(map[string]string)
	request.PublicAccessType = objectstorage.CreateBucketDetailsPublicAccessTypeNopublicaccess


        // print
	fmt.Println(*request.NamespaceName)         // abc123
	fmt.Println(*request.Name)                            // foobar123

	_, err := c.CreateBucket(ctx, request)             <<------ ERROR Occurs at this point

        // print
	fmt.Println("created?")                                   // created?

	helpers.FatalIfError(err)                                  // Service error:BadRequest. OCID doesn't match expected pattern or contains invalid characters. . http status code: 400. Opc request id: bom-1:COOQCl1oD-ZD9VZLXnz4CNWxSoncN88sajoiWJxDbbpPLs9QN03LuwtMT73u


	fmt.Println("create bucket")
}
```

**Comment by jodoglevy** [comment]
Oh, my mistake -- I did not realize this operation requires the id of the compartment to create the bucket in to be passed to it. But looks like that is required. Glad you were able to resolve this issue.

I will talk to the Object Storage service team to make this easier for others in the future, by having them update the error message they return to say which parameter is misformatted.

Current error message for this case:
`OCID doesn't match expected pattern or contains invalid characters`

Proposed error message for this case:
`Compartment ID OCID '<passed value from the request for compartment id goes here>' doesn't match expected pattern or contains invalid characters`

**Comment by retrofit2** [comment]
@jodoglevy Thanks

1. I have a question, Until sdk version updated, should i use compartmentId as hard-coded?

2. I hope adding new feature of bulk object upload to the next version of sdk
    multipart upload is supported now, but
    it seems that doesn't exist putting bulk objects yet. so i am using `for loop` for putObject(),
    and some performance issue seemed to exist, but i'm not sure this is about `for loop`

**Comment by jodoglevy** [comment]
Re item 1 - you should use whatever the compartment ID is, that you want to create the bucket within

Re item 2 - yes you'd want to use a loop if you have many objects you need to upload. however, instead of putObject, you probably should be using the UploadManager to upload each object. For more info see https://docs.oracle.com/en-us/iaas/tools/python/latest/upload-manager.html

**Comment by retrofit2** [comment]
@jodoglevy Thank you a lot for your help!

I will change my code with `UploadManager` as your advice.
You can close this issue, thank you so much!
