### ISSUE TITLE
Support for definedTags and freeFormTags

### ISSUE THREAD

**Issue by owainlewis** [oracle/oci-go-sdk#42]
We require support for tagging volumes (and other resources).

Update generated code to support `definedTags` and `freeFormTags` where appropriate. 

https://docs.us-phoenix-1.oraclecloud.com/api/#/en/iaas/20160918/requests/CreateVolumeDetails

https://docs.us-phoenix-1.oraclecloud.com/Content/General/Concepts/resourcetags.htm

**Comment by jhorwit2** [comment]
@jasonyin now that the client is GA could that branch be merged to master?

**Comment by jodoglevy** [comment]
@jhorwit2 we still want to do some more testing of this before merging it into the GA SDK. Goal is still to have this in by end of March. If you need it early, can you consume it from the other branch for now?

**Comment by jasonyin** [comment]
we have tagging for core and identity service in release V1.1.0 https://github.com/oracle/oci-go-sdk/releases/tag/v1.1.0 and will update for other services in coming releases.

**Comment by jasonyin** [comment]
closing this issue. V1.2.0 release has the last missing tagging resources (object storage).
