### ISSUE TITLE
Is there any existing/new API for getting the number of child table available in a NoSQL table?

### ISSUE THREAD

**Issue by ParthaI** [oracle/oci-go-sdk#422]
Dear team,

I would like to get the number of child table/child table info for a given NoSQL table name.

There are no such property/attributes in  [ListTables](https://pkg.go.dev/github.com/oracle/oci-go-sdk@v24.3.0+incompatible/nosql#NosqlClient.ListTables)/ [GetTable](https://pkg.go.dev/github.com/oracle/oci-go-sdk@v24.3.0+incompatible/nosql#NosqlClient.GetTable) which will help us to get the information of the child tables.

Is there any separate API call which will help me to get these information?

Thanks!

![5CA8172F-99A4-4D83-A3D9-5CBECE2B1F48_4_5005_c](https://user-images.githubusercontent.com/65847563/210724814-adee0924-2712-46d1-925a-f627a807b077.jpeg)

**Comment by dario-vega** [comment]
You can use the parameter Name 
https://pkg.go.dev/github.com/oracle/oci-go-sdk@v24.3.0+incompatible/nosql#ListTablesRequest
```
// A shell-globbing-style (*?[]) filter for names.
Name * [string](https://pkg.go.dev/builtin#string) `mandatory:"false" contributesTo:"query" name:"name"`
```

Some examples
```
name=table_a* <- all hierarchy including the parent (table_a)
name=table_a.* <- all hierarchy without the parent (table_a)
name=*.* <- all child tables in a compartment
name =* the default is all the tables in a compartment
```
using oci-cli for simplicity - here is with the output for `name=table_a*`
```
$ oci nosql table list --compartment-id ocid1.xxxx--name "table_a*" --query 'data.items[*].name'
[
  "table_a.table_b.table_w",
  "table_a.table_b.table_c",
  "table_a.table_b",
  "table_a"
]
```
The table name for a child table is done by using a composite name (a name_path) for the child table. A composite name consists of a number N (N > 1) of identifiers separated by dots. The last identifier is the local name of the child table and the first N-1 identifiers are the name of the parent

A parent table and its child tables are always in the same compartment.

**Comment by ParthaI** [comment]
Thanks @dario-vega for the information. I will give it a try and will let you know.
