### ISSUE TITLE
Operation fails with NotAuthorizedOrNotFound but same operation succeeds when using CLI

### ISSUE THREAD

**Issue by call-a3** [oracle/oci-go-sdk#435]
I'm using [dns.PatchZoneRecords](https://github.com/oracle/oci-go-sdk/blob/6604dd0ac46d971a907668f4b88538fc7050dad7/dns/dns_client.go#L2640) (underlying call `PATCH /20180115/zones/zone.name.here./records` ) to create a TXT record.
The request body (from setting OCI_GO_SDK_DEBUG=info) looks like
```
{"items":[{"domain":"record.subdomain.zone.name.here","operation":"ADD","rdata":"some arbitrary data","rtype":"TXT","ttl":60}]}
```

This results in a 404 response with body `{"code":"NotAuthorizedOrNotFound","message":"Authorization failed or requested resource not found."}`

Reading the documentation hints, this could either be because:
- the zone does not exist. I've checked, it does
- the credentials used don't have the necessary permissions. I've checked, it does.

To test my sanity on the above two points, I've attempted to recreate the same operation using the oci command line tool:
I'm using the same credentials as the SDK

`oci --profile SDKCREDS dns record zone patch --zone-name-or-id zone.name.here. --items '{"items":[{"domain":"record.subdomain.zone.name.here","operation":"ADD","rdata":"some arbitrary data","rtype":"TXT","ttl":60}]}`

This operation succeeds without errors.

What gives? Could there be a bug in the authorization code/signature generation of the SDK? Or is there something I might be missing?

**Comment by KartikShrikantHegde** [comment]
Hi @call-a3 , could you share details on which SDK version and which platform are you running your code on? Also, how are you reading the config file in SDK - directly inside the code or from a file or env variable?

If you can share the error log, that would be helpful too. If it works using CLI but in SDK doesn't mean there might be a bug in SDK (could be). Have you verified the permissions you have (region, compartment, policy etc.) matches with configuration settings?

**Comment by KartikShrikantHegde** [comment]
@call-a3 DNS team will take a look at this and get back to you.

**Comment by tfountain** [comment]
The OCI CLI uses the OCI SDK behind the scenes, so the same operation is being called in both cases. There must be a difference between the two requests, it's a question of figuring out what that difference is. Unfortunately we would need the opc-request-id to do that definitively. 

If you don't want to provide a request id here, please [open an Oracle support](https://docs.oracle.com/en-us/iaas/Content/GSG/Tasks/contactingsupport_topic-Open_a_support_service_request.htm) ticket and include the opc-request-id there. It would  be useful to provide the opc-request-id for a request that worked using the OCI CLI (for comparison). As this ticket is a few weeks old, it might be worth providing request ids for a more recent attempt.

I'm assuming from what you said that you are trying to modify records for a public DNS zone. If you are in fact trying to modify a private DNS zone, you would need to provide the view id (and possibly scope) parameters as well, as private DNS zones cannot be uniquely identified by name.

**Comment by call-a3** [comment]
Hi, I'll try to include some recent request id's shortly.
I've already opened a support ticket, but after some preliminary investigation they basically said to wait and see what comes out of this ticket ;) 

What we did manage to discover through the SR so far though, is that (for reasons unclear to me) the program that I'm working on seems to be using instance credentials (as described [here](https://docs.oracle.com/en-us/iaas/Content/Identity/Tasks/callingservicesfrominstances.htm) instead of the user credentials that are configured for it.
To provide some context here:
- the program I'm working on is a cert-manager-webhook, it adds and removes DNS TXT records to be able to pass DNS verification for ACME challenges
- the program is deployed on an (OCI-managed) K8S cluster
- the tenancy that OCI K8S cluster is running in, is not the same tenancy as the one that controls the DNS zone

So (if my understanding/intuition is correct) it would appear that somehow the program detects that it is running as a container on an OCI-managed K8S node (which is ofc an OCI compute instance) and as a result uses that instances' credentials somehow. Or (although even suggesting this makes me feel crazy) the OCI backend detects that the requests are coming from an OCI instance IP and expects to get instance credentials based on that.

Final note: I am trying to modify a public DNS zone.

**Comment by tfountain** [comment]
Your last bullet point there is likely to be relevant. If the zone lives in another tenancy, you would need to have cross-tenancy policies (endorse... admit...) in place to allow your K8S tenancy to modify the zone. Typically these would give a user group access to make the change, but if your call is using instance credentials, your instance wouldn't be a member of that user group. 

Instead you probably want to create a dynamic group which the instance would be a member of: https://docs.oracle.com/en-us/iaas/Content/Identity/Tasks/managingdynamicgroups.htm, and then you'd need to have endorse and admit policies to allow that dynamic group to modify DNS records on the zone.

**Comment by call-a3** [comment]
Ah, turns out (through turning on higher-verbosity logging) that RBAC rules weren't set correctly so the code did not have access to the secret that contained the correct OCI credentials. When it fails to load the config from the configured secret, it falls back to using instance credentials, which was the source of confusion for me.
By providing the correct RBAC rule the SDK now can use the correct credentials and the operation succeeds.

Thanks for sticking with me!
