### ISSUE TITLE
SDK testability and mocks

### ISSUE THREAD

**Issue by luispdm** [oracle/oci-go-sdk#438]
Hi all.

I am looking into the possibility of leveraging the Oracle Cloud for a hobby project. The services the project will be interacting with are Queues and NoSQL. Having said that, I have a couple of questions related to unit and integration testing:

- is there a software/tool able to emulate the entire (or part of it) Oracle Cloud infrastructure locally? The only simulator I found is the one for the NoSQL service https://www.oracle.com/downloads/cloud/nosql-cloud-sdk-downloads.html
- which SDK for the NoSQL service should one use? The module inside this repo or the one here https://github.com/oracle/nosql-go-sdk? The latter gives the possibility to use the simulator. I'd like to have only one dependency but if I go with the module in this repo I won't be able to use the NoSQL simulator
- is there an easy way to mock the OCI SDK? I see a person asked a similar question some years ago https://github.com/oracle/oci-go-sdk/issues/10

I posted these questions some days ago in the Oracle forum already https://forums.oracle.com/ords/apexds/post/go-sdk-cloud-simulator-8400 but I feel like this is the best place to ask as they might have a better reach.

If you think they are irrelevant to this repo, I would appreciate it if you could point me to an appropriate website/forum.

Thanks a lot!

**Comment by KartikShrikantHegde** [comment]
Hi @luispdm ,

Unfortunately, there a NO tool to emulate the entire Oracle Cloud infrastructure APIs locally. And you are right NoSQL does offer a simulator for the NoSQL service. I will ask the NoSQL team to give guidance on which SDK you should use for your use case. We will come back with a response in this thread.

**Comment by luispdm** [comment]
Hi @KartikShrikantHegde . Thanks for your reply. There's no such simulator for the queues service at least?

**Comment by KartikShrikantHegde** [comment]
Hi @luispdm , Let me check with the queue service team, but as far as I know, they don't have one either.

**Comment by connelly38** [comment]
@luispdm  For noSQL operations you can use the noSQL cloud simulator. But that does not simulate anything other than the noSQL cloud service. 

If there's nothing more to do here, can we close this issue please?

**Comment by jyotisaini** [comment]
Hi @luispdm We haven't heard back from you in a long time. I'm closing this issue for now. Feel free to reopen if you need further assistance.
