### ISSUE TITLE
Unable to retrieve actual object storage bucket size

### ISSUE THREAD

**Issue by bigdatasourav** [oracle/oci-go-sdk#443]
I am trying to fetch the actual object storage bucket size. Here is a bucket I have with a few objects - 
  
<img width="1484" alt="image" src="https://github.com/oracle/oci-go-sdk/assets/78197905/281cfcf3-6813-4801-85b8-aa3d8b8db4d9">

Here in the console, the bucket's Approximate Size is available, which is 6.94 KiB. Also, I have three objects with sizes - 5.53 KiB, 13 bytes and 1.4 KiB.

Here are the APIs I have executed to fetch the values -
For Approximate Size, I ran the GetBucket API present in ObjectStorageClient, but in response, I received nil.
As per the API documentation, this API should provide me with the Approximate Size of a bucket.

For object size, I executed the ListObjects API present in ObjectStorageClient; in response, I received the following - 

object1 - Actual size is 5.53 KiB as per the console
From API, I received - 5659 bytes which is 5.52 KiB

object2 - Actual size is 13 bytes as per the console
From API, I received - 13 bytes

object3 - Actual size is 1.4 KiB as per the console
From API, I received - 1430 bytes which is 1.39 KiB

So, the ListObjects API always returns an approximate value, not the actual. With many buckets and large objects, this becomes a huge difference between actual and approximate values.

Expectation - 
1. The GetBucket API should return the Approximate Size of a bucket.
2. The ListObjects API should return the actual size of an object.

**Comment by KartikShrikantHegde** [comment]
Hi @bigdatasourav , Can you please clarify which Go SDK version are you using?

**Comment by bigdatasourav** [comment]
Hey @KartikShrikantHegde, we are using v65.28.0.

**Comment by KartikShrikantHegde** [comment]
Hi @bigdatasourav ,

I just heard from the Object Storage team. They indicated that it is expected behavior and the confusion caused by the console rounding the sizes (which is the right thing to do)

Here is their observation:

object1 - Actual size is 5.53 KiB as per the console
From API, received size - 5659 bytes which is 5.52 KiB
5659 / 1024 = 5.5263671875 and that rounds up to 5.53KiB

Let us know if you have any questions.

**Comment by jyotisaini** [comment]
Hi @bigdatasourav We haven't heard back from you for quite some time. I'm closing the ticket. Please feel free to reopen if you need further assistance.
