### ISSUE TITLE
Retry policy does not retry ephemeral network errors

### ISSUE THREAD

**Issue by pcd1193182** [oracle/oci-go-sdk#447]
I recently had a PutObject request fail with a `connection reset by peer` error message. My retry policy is configured for infinite retries with backoff. This error was not retried, and was propagated up to the application level, where a crash occurred.  It looks to me like IsNetworkError in errors.go is supposed to handle this case, but it uses the now-deprecated `net.Error.Temporary()` function. The error message looks like `"https://objectstorage.us-phoenix-1.oraclecloud.com/...": read tcp 10.164.18.204:60368->134.70.8.1:443: read: connection reset by peer`. Is there another concise way to handle networking issues like this one?

**Comment by JoshuaWR** [comment]
Hi @pcd1193182, we are looking into the issue, and need a bit more information. Could you please share how you are configuring your retry policy, as well as confirm whether or not it is successfully calling the isNetworkError() Function? Thank you! We plan to replace the Temporary() function call, however according to our tests it should be able to successfully catch the "connection reset by peer" error.

**Comment by pcd1193182** [comment]
@JoshuaWR The retry policy is configured with the following lines:
```
	retryCountRateLimitErrors := func(r common.OCIOperationResponse) bool {
		if r.Error == nil && r.Response.HTTPResponse().StatusCode == 429 {
			clientInfo.rate_limit_errors.Add(1)
		}
		return common.DefaultShouldRetryOperation(r)
	}
	retryPolicy := common.NewRetryPolicyWithOptions(
		common.WithUnlimitedAttempts(time.Duration(24*time.Hour)),
		common.WithExponentialBackoff(time.Duration(10*time.Second), 2),
		common.WithShouldRetryOperation(retryCountRateLimitErrors),
        )
```

I was not able to positively determine that the IsNetworkError() function was being called, but in the case where r.Error is not nil IsNetworkError is the first function called in the DefaultShouldRetryOperation path. The specific stringified version of the error was `Put "https://objectstorage.us-phoenix-1.oraclecloud.com/...": read tcp 10.164.18.204:60368->134.70.8.1:443: read: connection reset by peer`, which, as I understand the way the error string formatting, indicates that r.Error should not be nil.

**Comment by JoshuaWR** [comment]
@pcd1193182, thanks for giving us that information. Could you try changing the code for IsNetworkError() inside of common/errors.go to look like the following, and let us know if that solves your problem? Thank you.
![Screenshot 2023-08-17 at 10 05 10 AM](https://github.com/oracle/oci-go-sdk/assets/140859979/58404912-cc2c-4c38-a1a4-123886c6c1ac)

**Comment by pcd1193182** [comment]
@JoshuaWR I have applied a similar patch and haven't seen the issue since I reported it; however, the issue was not easy to trigger in the first place (required a large amount of stress testing), so I can't be certain if the mitigation worked or if it was just not encountered during testing.

**Comment by JoshuaWR** [comment]
@pcd1193182 This fix is now in the public SDK Github. Closing this issue.
