### ISSUE TITLE
Token not present in Identity Domains' `CreateAuthTokenResponse` and `CreateMyAuthTokenResponse` 

### ISSUE THREAD

**Issue by F21** [oracle/oci-go-sdk#448]
The `token` seems to be missing from the following response types for the `IdentityDomainsClient`:
- [`CreateAuthTokenResponse`](https://pkg.go.dev/github.com/oracle/oci-go-sdk/v65@v65.46.0/identitydomains#CreateAuthTokenResponse)
- [`CreateMyAuthTokenResponse`](https://pkg.go.dev/github.com/oracle/oci-go-sdk/v65@v65.46.0/identitydomains#CreateMyAuthTokenResponse)

Since it is not possible to get the token back after creating them, the `CreateAuthToken` and `CreateMyAuthToken` methods are a bit useless.

I did trace the request when creating auth tokens using the OCI dashboard and it appears that a `token` attribute was returned in the response, so the value appears to be there, just not in the [API documentation](https://docs.oracle.com/en/cloud/paas/iam-domains-rest-api/op-admin-v1-authtokens-post.html) and the SDK.

**Comment by KartikShrikantHegde** [comment]
@F21 thanks for reporting the issue, we will have Identity look at this and confirm.

**Comment by jyotisaini** [comment]
Hi @F21 I quickly checked the CreateAuthTokenResponse & CreateMyAuthTokenResponse and in both the response objects we do get back AuthToken and MyAuthToken respectively. 

Create Auth token response  - https://github.com/oracle/oci-go-sdk/blob/master/identitydomains/create_auth_token_request_response.go#L108 
Create my auth token response - https://github.com/oracle/oci-go-sdk/blob/master/identitydomains/create_my_auth_token_request_response.go#L96

its also mentioned in the Go SDK API refrence -  https://docs.oracle.com/en-us/iaas/tools/go/65.46.0/identitydomains/index.html#CreateAuthTokenResponse 
https://docs.oracle.com/en-us/iaas/tools/go/65.46.0/identitydomains/index.html#CreateMyAuthTokenResponse

**Comment by F21** [comment]
@jyotisaini I need the contents of the auth token, because I am using Terraform to create the auth tokens and need to set the actual tokens as secrets in my application/deployment.

Is there any other way to retrieve the content of the token after creation? There doesn't seem to be any use-case where one would create the auth token without being able to retrieve the content of the token.

Interestingly, if I create an auth token using the identity service (not identity domains), I am able to get the token back. See [AuthToken](https://docs.oracle.com/en-us/iaas/api/#/en/identity/20160918/AuthToken/) which is returned by [CreateAuthToken](https://docs.oracle.com/en-us/iaas/api/#/en/identity/20160918/AuthToken/CreateAuthToken)

**Comment by F21** [comment]
Any updates for this one? This is a pretty big blocker for us.

**Comment by F21** [comment]
Any update for this one?

**Comment by jyotisaini** [comment]
This has been released today. Closing the issue.
