### ISSUE TITLE
missing LaunchOptions in CreateImageDetails struct

### ISSUE THREAD

**Issue by procolost** [oracle/oci-go-sdk#449]
hello i need force firmware type when import, python sdk provide LaunchOptions.
but in go this field is missing 

https://docs.oracle.com/en-us/iaas/api/#/en/iaas/20160918/datatypes/CreateImageDetails

**Comment by KartikShrikantHegde** [comment]
Hi @procolost , Can you please point to the Go and Python SDK code that you used? Did you try using `LaunchOptions` field in your code and did it throw an error? If so can you share the error details as well. Thanks.

**Comment by KartikShrikantHegde** [comment]
Hi @procolost , Can you please look at the above comment and provide more details? Thanks.

**Comment by KartikShrikantHegde** [comment]
Hi @procolost, I am closing this ticket for now, please feel free to create a re-open if you are still facing the issue. Thanks.
