### ISSUE TITLE
Issue with endpoint - Oracle Queue

### ISSUE THREAD

**Issue by PedroSousaEquals** [oracle/oci-go-sdk#467]
Hello, I'm using the GO SDK for queue services, but I encountered an error when using it:

 Message Error: Please use endpoint https://cell-1.queue.messaging.sa-vinhedo-1.oci.oraclecloud.com\nOperation Name: GetMessages\nTimestamp: 2023-11-10 18:40:57.086135167 -0300 - 03 m=+140.026919796\nClient Version: Oracle-GoSDK/65.49.1\nRequest Endpoint: GET

When I looked at queue/queue_client.go I saw that the endpoint is like:

`https://messaging.{region}.oci.{secondLevelDomain}`

in queue/queue_client.go line 68

```
// SetRegion overrides the region of this client.
func (client *QueueClient) SetRegion(region string) {
	client.Host = common.StringToRegion(region).EndpointForTemplate("queue", "https://messaging.{region}.oci.{secondLevelDomain}")
}
```

when changing to

`https://cell-1.oracle.queue.{region}.oci.{secondLevelDomain}`

the error disappears. Can you help me? 

My function:

`	
req := queue.GetMessagesRequest{
	
	Limit:               common.Int(11),
	QueueId:             common.String("ocid1.queue.oc1.sa-vinhedo-1.*********"),
	TimeoutInSeconds:    common.Int(22),
	VisibilityInSeconds: common.Int(9353)}

	resp, err := queueClient.GetMessages(context.Background(), req)
	if err != nil {
		return err
	}`

**Comment by SAURAVDX007** [comment]
Is there any update on this? Even I am facing same issue.

**Comment by JoshuaWR** [comment]
Hi @PedroSousaEquals @SAURAVDX007, sorry for the late response. Have you tried setting the endpoint manually in your code? ie: 
 
--> **queueClient.Host = https://cell-1.queue.messaging.sa-vinhedo-1.oci.oraclecloud.com**
resp, err := queueClient.GetMessages(context.Background(), req)
if err != nil {
	return err
}

Please let us know if this helps, thanks!

**Comment by JoshuaWR** [comment]
@PedroSousaEquals Have you tried this solution as well? Let us know if it works for you, thanks!

**Comment by PedroSousaEquals** [comment]
Hi @JoshuaWR , Yes... apologies for the delay, but it works, thanks !
