### ISSUE TITLE
Object Store Upload Part API Does not return etag.

### ISSUE THREAD

**Issue by vshiva** [oracle/oci-go-sdk#64]
I'm trying to do a multipart upload of a huge object to object store using the sdk. 

The UploadPart in objectstoreage_client.go ignores the etag value that is returned. This value is needed later to commit the upload. With out the etag of the part it is not possible to use multipart upload feature and go-sdk.

Here is the Upload Method.
```go
func (client ObjectStorageClient) UploadPart(ctx context.Context, request UploadPartRequest) (err error) {
	httpRequest, err := common.MakeDefaultHTTPRequestWithTaggedStruct(http.MethodPut, "/n/{namespaceName}/b/{bucketName}/u/{objectName}", request)
	if err != nil {
		return
	}
	_, err = client.Call(ctx, &httpRequest)
	return
}
```

**Comment by gcstang** [comment]
@vshiva did you get multipart to work?
I ran into an issue and was wondering if you got past this or have an idea why it might be happening.
#105

**Comment by vshiva** [comment]
Yeah. I'm able to get it to work with the latest/being on the master.
