### ISSUE TITLE
Support custom loggers

### ISSUE THREAD

**Issue by jhorwit2** [oracle/oci-go-sdk#8]
Many projects using this SDK will have their own logger whether that's glog, logrus or whatever. Consumers should have the ability to use whatever logger they wish for client logs given it meets the required interface of the SDK.

**Comment by eginez** [comment]
@jhorwit2 We have tentative interface we'd like to make public and enable custom logger, would appreciate your input. You can find the interface here: https://github.com/oracle/oci-go-sdk/blob/master/common/log.go#L15

**Comment by jodoglevy** [comment]
@jhorwit2  can you review Esteban's comment above please?

**Comment by jasonyin** [comment]
@jhorwit2 pls let me know if that works for you or not, so I can get it merged, thanks!

**Comment by jhorwit2** [comment]
@jasonyin @jodoglevy That would work but it would be nicer if it had Infof, Debugf, etc on the interface since most loggers already have those methods which makes writing a wrapper not needed.

**Comment by jasonyin** [comment]
thanks @jhorwit2  for the reply, does 'LogLevel' work for you in this case? similar like Log.(Info,....) Log.(Debug,...) etc....

**Comment by jasonyin** [comment]
feel free to re-open it if 'LogLevel' doesn't work for you.
