### ISSUE TITLE
Composing configuration provider panics / isnt usable

### ISSUE THREAD

**Issue by jhorwit2** [oracle/oci-go-sdk#86]
it seems that if there is an incorrect config provider first it panics every time. If i put `p2` first then it'll work. If `p4` or `p1` are first then it panics. 
 
```
	p1, _ := common.ConfigurationProviderFromFile(os.Getenv("OCI_CONFIG_FILE"), "")
	p2, _ := common.ConfigurationProviderFromFile(path.Join(os.Getenv("HOME"), ".oci", "config"), "")
	p4 := common.ConfigurationProviderEnvironmentVariables("OCI", os.Getenv("OCI_PRIVATE_KEY_PASSWORD"))
	provider, err := common.ComposingConfigurationProvider([]common.ConfigurationProvider{
		p4, p1, p2,
	})
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1ed60b7]

goroutine 77 [running]:
path/vendor/github.com/oracle/oci-go-sdk/common.composingConfigurationProvider.TenancyOCID(0xc4202028a0, 0x3, 0x3, 0x0, 0xc420496700, 0xc420496700, 0x48028b0)
	/Users/horwitz/gocode/src/path/vendor/github.com/oracle/oci-go-sdk/common/configuration.go:431 +0x57
path/vendor/github.com/oracle/oci-go-sdk/common.(*composingConfigurationProvider).TenancyOCID(0xc42000c6e0, 0xc4205934d8, 0x1012867, 0x4863008, 0xc4204df4c0)
	<autogenerated>:1 +0x4e
path/vendor/github.com/oracle/oci-go-sdk/common.(ConfigurationProvider).TenancyOCID-fm(0xc42000c601, 0x100070120255810, 0x0, 0x1a)
	/Users/horwitz/gocode/src/path/vendor/github.com/oracle/oci-go-sdk/common/configuration.go:25 +0x2f
path/vendor/github.com/oracle/oci-go-sdk/common.IsConfigurationProviderValid(0x2eea360, 0xc42000c6e0, 0x1048bd8, 0xc4204df4d4, 0x23b1fc6)
	/Users/horwitz/gocode/src/path/vendor/github.com/oracle/oci-go-sdk/common/configuration.go:27 +0x1b7
path/vendor/github.com/oracle/oci-go-sdk/common.NewClientWithConfig(0x2eea360, 0xc42000c6e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/horwitz/gocode/src/path/vendor/github.com/oracle/oci-go-sdk/common/client.go:99 +0x7b
path/vendor/github.com/oracle/oci-go-sdk/core.NewComputeClientWithConfigurationProvider(0x2eea360, 0xc42000c6e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/horwitz/gocode/src/path/vendor/github.com/oracle/oci-go-sdk/core/core_compute_client.go:27 +0x9d
```

**Comment by eginez** [comment]
@jhorwit2 I am having a bit of trouble replicating this issue. Quick q, if you were to run `common.IsConfigurationProviderValid(provider)` does it panic?

**Comment by eginez** [comment]
Hi @jhorwit2 I found a fix for this issue and it will be released on the next release cycle, something to note is that you should probably be checking for errors when createing p1, and p2. For example if the env variable "OCI_CONFIG_FILE" is not set it will return the empty string. The `ConfigurationProviderFromFile` returns an error on empty strings and a nil provider.

**Comment by jhorwit2** [comment]
@eginez Ideally, the composing configuration provider should only error if none succeeded. In my experience, this is typically the case for clients that do similar logic. For example, the kubernetes client does this. It checks for config sources based on precedence then only errors if none succeed. I don't see much value in using the composing config provider if i need to check for each one explicitly. My 0.02.

**Comment by eginez** [comment]
That is correct, the ComposingConfiguration provider only fails if none of its parts succeed, however it expects that all of its parts to be non nil at creation time
